package com.terrydr.domain.pathology;

import java.util.Date;

/**
 * @author zyyan@terrydr.com
 * @version 1.0.0
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 */
public class PathologyReportDetail {

    private Integer baseDoctorId;

    private String shareId;

    private String doctorName;

    private String doctorTeleno;

    private String doctorAvatar;

    private String hospitalName;

    private String reportHospName;

    private String sendDate="";

    private String submitMaterial;

    private String clinicalSymptom;

    private String pathDiagnosis;

    private String visualFeature;

    private String microscopeFeature;

    public void setS0(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS1(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS2(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS3(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS4(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS5(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS6(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS7(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }

    public void setS8(String s0) {
        if (s0 != null && s0.length() > 0)
            this.sendDate += s0;
    }


    public String getSendDate() {
        return sendDate;
    }

    public void setSendDate(String sendDate) {
        this.sendDate = sendDate;
    }

    public String getSubmitMaterial() {
        return submitMaterial;
    }

    public void setSubmitMaterial(String submitMaterial) {
        this.submitMaterial = submitMaterial;
    }

    public String getClinicalSymptom() {
        return clinicalSymptom;
    }

    public void setClinicalSymptom(String clinicalSymptom) {
        this.clinicalSymptom = clinicalSymptom;
    }

    public String getPathDiagnosis() {
        return pathDiagnosis;
    }

    public void setPathDiagnosis(String pathDiagnosis) {
        this.pathDiagnosis = pathDiagnosis;
    }

    public String getVisualFeature() {
        return visualFeature;
    }

    public void setVisualFeature(String visualFeature) {
        this.visualFeature = visualFeature;
    }

    public String getMicroscopeFeature() {
        return microscopeFeature;
    }

    public void setMicroscopeFeature(String microscopeFeature) {
        this.microscopeFeature = microscopeFeature;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_id
     *
     * @mbg.generated
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_type
     *
     * @mbg.generated
     */
    private Integer reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.patient_id
     *
     * @mbg.generated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_hosp_id
     *
     * @mbg.generated
     */
    private Integer reportHospId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.submit_unit
     *
     * @mbg.generated
     */
    private String submitUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.submit_doctor
     *
     * @mbg.generated
     */
    private String submitDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.submit_department
     *
     * @mbg.generated
     */
    private String submitDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.admission_no
     *
     * @mbg.generated
     */
    private String admissionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.bed_no
     *
     * @mbg.generated
     */
    private String bedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.clinical_diagnosis
     *
     * @mbg.generated
     */
    private String clinicalDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_img
     *
     * @mbg.generated
     */
    private String reportImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.exam_date
     *
     * @mbg.generated
     */
    private Date examDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.is_enterprise
     *
     * @mbg.generated
     */
    private Integer isEnterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.proc_inst_id
     *
     * @mbg.generated
     */
    private String procInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.process_status
     *
     * @mbg.generated
     */
    private Integer processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_tag
     *
     * @mbg.generated
     */
    private Integer reportTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.final_tag
     *
     * @mbg.generated
     */
    private Integer finalTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_id
     *
     * @return the value of t_report.report_id
     * @mbg.generated
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_id
     *
     * @param reportId the value for t_report.report_id
     * @mbg.generated
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_type
     *
     * @return the value of t_report.report_type
     * @mbg.generated
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_type
     *
     * @param reportType the value for t_report.report_type
     * @mbg.generated
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.doctor_id
     *
     * @return the value of t_report.doctor_id
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.doctor_id
     *
     * @param doctorId the value for t_report.doctor_id
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.patient_id
     *
     * @return the value of t_report.patient_id
     * @mbg.generated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.patient_id
     *
     * @param patientId the value for t_report.patient_id
     * @mbg.generated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.record_id
     *
     * @return the value of t_report.record_id
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.record_id
     *
     * @param recordId the value for t_report.record_id
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.hospital_id
     *
     * @return the value of t_report.hospital_id
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.hospital_id
     *
     * @param hospitalId the value for t_report.hospital_id
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_hosp_id
     *
     * @return the value of t_report.report_hosp_id
     * @mbg.generated
     */
    public Integer getReportHospId() {
        return reportHospId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_hosp_id
     *
     * @param reportHospId the value for t_report.report_hosp_id
     * @mbg.generated
     */
    public void setReportHospId(Integer reportHospId) {
        this.reportHospId = reportHospId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.submit_unit
     *
     * @return the value of t_report.submit_unit
     * @mbg.generated
     */
    public String getSubmitUnit() {
        return submitUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.submit_unit
     *
     * @param submitUnit the value for t_report.submit_unit
     * @mbg.generated
     */
    public void setSubmitUnit(String submitUnit) {
        this.submitUnit = submitUnit == null ? null : submitUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.submit_doctor
     *
     * @return the value of t_report.submit_doctor
     * @mbg.generated
     */
    public String getSubmitDoctor() {
        return submitDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.submit_doctor
     *
     * @param submitDoctor the value for t_report.submit_doctor
     * @mbg.generated
     */
    public void setSubmitDoctor(String submitDoctor) {
        this.submitDoctor = submitDoctor == null ? null : submitDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.submit_department
     *
     * @return the value of t_report.submit_department
     * @mbg.generated
     */
    public String getSubmitDepartment() {
        return submitDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.submit_department
     *
     * @param submitDepartment the value for t_report.submit_department
     * @mbg.generated
     */
    public void setSubmitDepartment(String submitDepartment) {
        this.submitDepartment = submitDepartment == null ? null : submitDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.admission_no
     *
     * @return the value of t_report.admission_no
     * @mbg.generated
     */
    public String getAdmissionNo() {
        return admissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.admission_no
     *
     * @param admissionNo the value for t_report.admission_no
     * @mbg.generated
     */
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo == null ? null : admissionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.bed_no
     *
     * @return the value of t_report.bed_no
     * @mbg.generated
     */
    public String getBedNo() {
        return bedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.bed_no
     *
     * @param bedNo the value for t_report.bed_no
     * @mbg.generated
     */
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo == null ? null : bedNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.clinical_diagnosis
     *
     * @return the value of t_report.clinical_diagnosis
     * @mbg.generated
     */
    public String getClinicalDiagnosis() {
        return clinicalDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.clinical_diagnosis
     *
     * @param clinicalDiagnosis the value for t_report.clinical_diagnosis
     * @mbg.generated
     */
    public void setClinicalDiagnosis(String clinicalDiagnosis) {
        this.clinicalDiagnosis = clinicalDiagnosis == null ? null : clinicalDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_img
     *
     * @return the value of t_report.report_img
     * @mbg.generated
     */
    public String getReportImg() {
        return reportImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_img
     *
     * @param reportImg the value for t_report.report_img
     * @mbg.generated
     */
    public void setReportImg(String reportImg) {
        this.reportImg = reportImg == null ? null : reportImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.create_time
     *
     * @return the value of t_report.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.create_time
     *
     * @param createTime the value for t_report.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.is_deleted
     *
     * @return the value of t_report.is_deleted
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.is_deleted
     *
     * @param isDeleted the value for t_report.is_deleted
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.exam_date
     *
     * @return the value of t_report.exam_date
     * @mbg.generated
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.exam_date
     *
     * @param examDate the value for t_report.exam_date
     * @mbg.generated
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.remarks
     *
     * @return the value of t_report.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.remarks
     *
     * @param remarks the value for t_report.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.is_enterprise
     *
     * @return the value of t_report.is_enterprise
     * @mbg.generated
     */
    public Integer getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.is_enterprise
     *
     * @param isEnterprise the value for t_report.is_enterprise
     * @mbg.generated
     */
    public void setIsEnterprise(Integer isEnterprise) {
        this.isEnterprise = isEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.proc_inst_id
     *
     * @return the value of t_report.proc_inst_id
     * @mbg.generated
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.proc_inst_id
     *
     * @param procInstId the value for t_report.proc_inst_id
     * @mbg.generated
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.process_status
     *
     * @return the value of t_report.process_status
     * @mbg.generated
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.process_status
     *
     * @param processStatus the value for t_report.process_status
     * @mbg.generated
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_tag
     *
     * @return the value of t_report.report_tag
     * @mbg.generated
     */
    public Integer getReportTag() {
        return reportTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_tag
     *
     * @param reportTag the value for t_report.report_tag
     * @mbg.generated
     */
    public void setReportTag(Integer reportTag) {
        this.reportTag = reportTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.final_tag
     *
     * @return the value of t_report.final_tag
     * @mbg.generated
     */
    public Integer getFinalTag() {
        return finalTag;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.final_tag
     *
     * @param finalTag the value for t_report.final_tag
     * @mbg.generated
     */

    public void setFinalTag(Integer finalTag) {
        this.finalTag = finalTag;
    }

    public Integer getBaseDoctorId() {
        return baseDoctorId;
    }

    public void setBaseDoctorId(Integer baseDoctorId) {
        this.baseDoctorId = baseDoctorId;
    }

    public String getShareId() {
        return shareId;
    }

    public void setShareId(String shareId) {
        this.shareId = shareId;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public String getDoctorTeleno() {
        return doctorTeleno;
    }

    public void setDoctorTeleno(String doctorTeleno) {
        this.doctorTeleno = doctorTeleno;
    }

    public String getDoctorAvatar() {
        return doctorAvatar;
    }

    public void setDoctorAvatar(String doctorAvatar) {
        this.doctorAvatar = doctorAvatar;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public String getReportHospName() {
        return reportHospName;
    }

    public void setReportHospName(String reportHospName) {
        this.reportHospName = reportHospName;
    }
}