package com.terrydr.domain.pathology;

import com.terrydr.domain.FatherBean;
import com.terrydr.domain.PathologyInfo;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Date;

public class Pathology extends FatherBean{

    @Override
    public String toString() {
        return "Pathology_Info（ID=" + this.id + "）";
    }

    public Pathology(PathologyInfo pathologyInfo) {
        this.id = pathologyInfo.getId();
        this.pathologyMark = pathologyInfo.getPathologyMark();
        this.recordId = pathologyInfo.getRecordId();
        this.sectionNo = pathologyInfo.getSectionNo();
        this.photoCount = pathologyInfo.getPhotoCount();
        this.configInfo = pathologyInfo.getConfigInfo();
        this.previewPath = pathologyInfo.getPreviewPath();
        this.xmlPath = pathologyInfo.getXmlPath();
        this.layerPath = pathologyInfo.getLayerPath();
        this.status = pathologyInfo.getStatus();
        this.logicDel = pathologyInfo.getLogicDel();
        this.createTime = pathologyInfo.getCreateTime();
        this.compoundStartTime = pathologyInfo.getCompoundStartTime();
        this.compoundEndTime = pathologyInfo.getCompoundEndTime();
        this.scanRate = pathologyInfo.getScanRate();
        this.scanWidth = pathologyInfo.getScanWidth();
        this.scanHeight = pathologyInfo.getScanHeight();
        this.hdCount = pathologyInfo.getHdCount();
        this.overlap = pathologyInfo.getOverlap();
        this.tileSize = pathologyInfo.getTileSize();
        this.width = pathologyInfo.getWidth();
        this.height = pathologyInfo.getHeight();

        if(pathologyInfo.getResolution() != null){
            DecimalFormat df = new DecimalFormat("########.####");
            df.setRoundingMode(RoundingMode.HALF_UP);

            this.resolution = Double.valueOf(df.format(pathologyInfo.getResolution().doubleValue()));
        }


        this.isEmbed = pathologyInfo.getIsEmbed();
        this.composeSort = pathologyInfo.getComposeSort();
        this.clientType = pathologyInfo.getClientType();
        this.doctorId = pathologyInfo.getDoctorId();
        this.isDelete = pathologyInfo.getIsDelete();
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.pathology_mark
     *
     * @mbg.generated
     */
    private String pathologyMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.section_no
     *
     * @mbg.generated
     */
    private String sectionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.photo_count
     *
     * @mbg.generated
     */
    private Integer photoCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.config_info
     *
     * @mbg.generated
     */
    private String configInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.preview_path
     *
     * @mbg.generated
     */
    private String previewPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.xml_path
     *
     * @mbg.generated
     */
    private String xmlPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.layer_path
     *
     * @mbg.generated
     */
    private String layerPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.logic_del
     *
     * @mbg.generated
     */
    private String logicDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.compound_start_time
     *
     * @mbg.generated
     */
    private Date compoundStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.compound_end_time
     *
     * @mbg.generated
     */
    private Date compoundEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.scan_rate
     *
     * @mbg.generated
     */
    private String scanRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.scan_width
     *
     * @mbg.generated
     */
    private Integer scanWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.scan_height
     *
     * @mbg.generated
     */
    private Integer scanHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.hd_count
     *
     * @mbg.generated
     */
    private Integer hdCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.overlap
     *
     * @mbg.generated
     */
    private Integer overlap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.tile_size
     *
     * @mbg.generated
     */
    private Integer tileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.resolution
     *
     * @mbg.generated
     */
    private Double resolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.is_embed
     *
     * @mbg.generated
     */
    private Integer isEmbed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.compose_sort
     *
     * @mbg.generated
     */
    private Integer composeSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.client_type
     *
     * @mbg.generated
     */
    private Integer clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.id
     *
     * @return the value of t_pathology_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.id
     *
     * @param id the value for t_pathology_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.pathology_mark
     *
     * @return the value of t_pathology_info.pathology_mark
     *
     * @mbg.generated
     */
    public String getPathologyMark() {
        return pathologyMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.pathology_mark
     *
     * @param pathologyMark the value for t_pathology_info.pathology_mark
     *
     * @mbg.generated
     */
    public void setPathologyMark(String pathologyMark) {
        this.pathologyMark = pathologyMark == null ? null : pathologyMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.record_id
     *
     * @return the value of t_pathology_info.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.record_id
     *
     * @param recordId the value for t_pathology_info.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.section_no
     *
     * @return the value of t_pathology_info.section_no
     *
     * @mbg.generated
     */
    public String getSectionNo() {
        return sectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.section_no
     *
     * @param sectionNo the value for t_pathology_info.section_no
     *
     * @mbg.generated
     */
    public void setSectionNo(String sectionNo) {
        this.sectionNo = sectionNo == null ? null : sectionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.photo_count
     *
     * @return the value of t_pathology_info.photo_count
     *
     * @mbg.generated
     */
    public Integer getPhotoCount() {
        return photoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.photo_count
     *
     * @param photoCount the value for t_pathology_info.photo_count
     *
     * @mbg.generated
     */
    public void setPhotoCount(Integer photoCount) {
        this.photoCount = photoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.config_info
     *
     * @return the value of t_pathology_info.config_info
     *
     * @mbg.generated
     */
    public String getConfigInfo() {
        return configInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.config_info
     *
     * @param configInfo the value for t_pathology_info.config_info
     *
     * @mbg.generated
     */
    public void setConfigInfo(String configInfo) {
        this.configInfo = configInfo == null ? null : configInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.preview_path
     *
     * @return the value of t_pathology_info.preview_path
     *
     * @mbg.generated
     */
    public String getPreviewPath() {
        return previewPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.preview_path
     *
     * @param previewPath the value for t_pathology_info.preview_path
     *
     * @mbg.generated
     */
    public void setPreviewPath(String previewPath) {
        this.previewPath = previewPath == null ? null : previewPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.xml_path
     *
     * @return the value of t_pathology_info.xml_path
     *
     * @mbg.generated
     */
    public String getXmlPath() {
        return xmlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.xml_path
     *
     * @param xmlPath the value for t_pathology_info.xml_path
     *
     * @mbg.generated
     */
    public void setXmlPath(String xmlPath) {
        this.xmlPath = xmlPath == null ? null : xmlPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.layer_path
     *
     * @return the value of t_pathology_info.layer_path
     *
     * @mbg.generated
     */
    public String getLayerPath() {
        return layerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.layer_path
     *
     * @param layerPath the value for t_pathology_info.layer_path
     *
     * @mbg.generated
     */
    public void setLayerPath(String layerPath) {
        this.layerPath = layerPath == null ? null : layerPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.status
     *
     * @return the value of t_pathology_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.status
     *
     * @param status the value for t_pathology_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.logic_del
     *
     * @return the value of t_pathology_info.logic_del
     *
     * @mbg.generated
     */
    public String getLogicDel() {
        return logicDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.logic_del
     *
     * @param logicDel the value for t_pathology_info.logic_del
     *
     * @mbg.generated
     */
    public void setLogicDel(String logicDel) {
        this.logicDel = logicDel == null ? null : logicDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.create_time
     *
     * @return the value of t_pathology_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.create_time
     *
     * @param createTime the value for t_pathology_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.compound_start_time
     *
     * @return the value of t_pathology_info.compound_start_time
     *
     * @mbg.generated
     */
    public Date getCompoundStartTime() {
        return compoundStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.compound_start_time
     *
     * @param compoundStartTime the value for t_pathology_info.compound_start_time
     *
     * @mbg.generated
     */
    public void setCompoundStartTime(Date compoundStartTime) {
        this.compoundStartTime = compoundStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.compound_end_time
     *
     * @return the value of t_pathology_info.compound_end_time
     *
     * @mbg.generated
     */
    public Date getCompoundEndTime() {
        return compoundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.compound_end_time
     *
     * @param compoundEndTime the value for t_pathology_info.compound_end_time
     *
     * @mbg.generated
     */
    public void setCompoundEndTime(Date compoundEndTime) {
        this.compoundEndTime = compoundEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.scan_rate
     *
     * @return the value of t_pathology_info.scan_rate
     *
     * @mbg.generated
     */
    public String getScanRate() {
        return scanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.scan_rate
     *
     * @param scanRate the value for t_pathology_info.scan_rate
     *
     * @mbg.generated
     */
    public void setScanRate(String scanRate) {
        this.scanRate = scanRate == null ? null : scanRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.scan_width
     *
     * @return the value of t_pathology_info.scan_width
     *
     * @mbg.generated
     */
    public Integer getScanWidth() {
        return scanWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.scan_width
     *
     * @param scanWidth the value for t_pathology_info.scan_width
     *
     * @mbg.generated
     */
    public void setScanWidth(Integer scanWidth) {
        this.scanWidth = scanWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.scan_height
     *
     * @return the value of t_pathology_info.scan_height
     *
     * @mbg.generated
     */
    public Integer getScanHeight() {
        return scanHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.scan_height
     *
     * @param scanHeight the value for t_pathology_info.scan_height
     *
     * @mbg.generated
     */
    public void setScanHeight(Integer scanHeight) {
        this.scanHeight = scanHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.hd_count
     *
     * @return the value of t_pathology_info.hd_count
     *
     * @mbg.generated
     */
    public Integer getHdCount() {
        return hdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.hd_count
     *
     * @param hdCount the value for t_pathology_info.hd_count
     *
     * @mbg.generated
     */
    public void setHdCount(Integer hdCount) {
        this.hdCount = hdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.overlap
     *
     * @return the value of t_pathology_info.overlap
     *
     * @mbg.generated
     */
    public Integer getOverlap() {
        return overlap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.overlap
     *
     * @param overlap the value for t_pathology_info.overlap
     *
     * @mbg.generated
     */
    public void setOverlap(Integer overlap) {
        this.overlap = overlap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.tile_size
     *
     * @return the value of t_pathology_info.tile_size
     *
     * @mbg.generated
     */
    public Integer getTileSize() {
        return tileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.tile_size
     *
     * @param tileSize the value for t_pathology_info.tile_size
     *
     * @mbg.generated
     */
    public void setTileSize(Integer tileSize) {
        this.tileSize = tileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.width
     *
     * @return the value of t_pathology_info.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.width
     *
     * @param width the value for t_pathology_info.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.height
     *
     * @return the value of t_pathology_info.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.height
     *
     * @param height the value for t_pathology_info.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.resolution
     *
     * @return the value of t_pathology_info.resolution
     *
     * @mbg.generated
     */
    public Double getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.resolution
     *
     * @param resolution the value for t_pathology_info.resolution
     *
     * @mbg.generated
     */
    public void setResolution(Double resolution) {
        this.resolution = resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.is_embed
     *
     * @return the value of t_pathology_info.is_embed
     *
     * @mbg.generated
     */
    public Integer getIsEmbed() {
        return isEmbed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.is_embed
     *
     * @param isEmbed the value for t_pathology_info.is_embed
     *
     * @mbg.generated
     */
    public void setIsEmbed(Integer isEmbed) {
        this.isEmbed = isEmbed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.compose_sort
     *
     * @return the value of t_pathology_info.compose_sort
     *
     * @mbg.generated
     */
    public Integer getComposeSort() {
        return composeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.compose_sort
     *
     * @param composeSort the value for t_pathology_info.compose_sort
     *
     * @mbg.generated
     */
    public void setComposeSort(Integer composeSort) {
        this.composeSort = composeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.client_type
     *
     * @return the value of t_pathology_info.client_type
     *
     * @mbg.generated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.client_type
     *
     * @param clientType the value for t_pathology_info.client_type
     *
     * @mbg.generated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.doctor_id
     *
     * @return the value of t_pathology_info.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.doctor_id
     *
     * @param doctorId the value for t_pathology_info.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info.is_delete
     *
     * @return the value of t_pathology_info.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info.is_delete
     *
     * @param isDelete the value for t_pathology_info.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}