package com.terrydr.domain.pathology;

import com.terrydr.domain.FatherBean;
import com.terrydr.domain.PathologyInfoDetail;

import java.util.Date;

public class PathologyDetail extends FatherBean{

    public PathologyDetail(PathologyInfoDetail detail) {
        this.pathologyMark = detail.getPathologyMark();
        this.embedPathologyMark = detail.getEmbedPathologyMark();
        this.type = detail.getType();
        this.imgPath = detail.getImgPath();
        this.videoPath = detail.getVideoPath();
        this.scanRate = detail.getScanRate();
        this.createTime = detail.getCreateTime();
        this.doctorId = detail.getDoctorId();
        this.isDel = detail.getIsDel();
        this.x = detail.getX();
        this.y = detail.getY();
        this.width = detail.getWidth();
        this.height = detail.getHeight();
        this.imageIndex = detail.getImageIndex();
        this.annotationId = detail.getAnnotationId();
    }

    @Override
    public String toString() {
        return "Pathology_Info_Detail（PathMark=" + this.pathologyMark + "）";
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.pathology_mark
     *
     * @mbg.generated
     */
    private String pathologyMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.embed_pathology_mark
     *
     * @mbg.generated
     */
    private String embedPathologyMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.video_path
     *
     * @mbg.generated
     */
    private String videoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.scan_rate
     *
     * @mbg.generated
     */
    private Integer scanRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.is_del
     *
     * @mbg.generated
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.x
     *
     * @mbg.generated
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.y
     *
     * @mbg.generated
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.image_index
     *
     * @mbg.generated
     */
    private Integer imageIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_info_detail.annotation_id
     *
     * @mbg.generated
     */
    private Integer annotationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.pathology_mark
     *
     * @return the value of t_pathology_info_detail.pathology_mark
     *
     * @mbg.generated
     */
    public String getPathologyMark() {
        return pathologyMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.pathology_mark
     *
     * @param pathologyMark the value for t_pathology_info_detail.pathology_mark
     *
     * @mbg.generated
     */
    public void setPathologyMark(String pathologyMark) {
        this.pathologyMark = pathologyMark == null ? null : pathologyMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.embed_pathology_mark
     *
     * @return the value of t_pathology_info_detail.embed_pathology_mark
     *
     * @mbg.generated
     */
    public String getEmbedPathologyMark() {
        return embedPathologyMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.embed_pathology_mark
     *
     * @param embedPathologyMark the value for t_pathology_info_detail.embed_pathology_mark
     *
     * @mbg.generated
     */
    public void setEmbedPathologyMark(String embedPathologyMark) {
        this.embedPathologyMark = embedPathologyMark == null ? null : embedPathologyMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.type
     *
     * @return the value of t_pathology_info_detail.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.type
     *
     * @param type the value for t_pathology_info_detail.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.img_path
     *
     * @return the value of t_pathology_info_detail.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.img_path
     *
     * @param imgPath the value for t_pathology_info_detail.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.video_path
     *
     * @return the value of t_pathology_info_detail.video_path
     *
     * @mbg.generated
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.video_path
     *
     * @param videoPath the value for t_pathology_info_detail.video_path
     *
     * @mbg.generated
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath == null ? null : videoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.scan_rate
     *
     * @return the value of t_pathology_info_detail.scan_rate
     *
     * @mbg.generated
     */
    public Integer getScanRate() {
        return scanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.scan_rate
     *
     * @param scanRate the value for t_pathology_info_detail.scan_rate
     *
     * @mbg.generated
     */
    public void setScanRate(Integer scanRate) {
        this.scanRate = scanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.create_time
     *
     * @return the value of t_pathology_info_detail.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.create_time
     *
     * @param createTime the value for t_pathology_info_detail.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.doctor_id
     *
     * @return the value of t_pathology_info_detail.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.doctor_id
     *
     * @param doctorId the value for t_pathology_info_detail.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.is_del
     *
     * @return the value of t_pathology_info_detail.is_del
     *
     * @mbg.generated
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.is_del
     *
     * @param isDel the value for t_pathology_info_detail.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.x
     *
     * @return the value of t_pathology_info_detail.x
     *
     * @mbg.generated
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.x
     *
     * @param x the value for t_pathology_info_detail.x
     *
     * @mbg.generated
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.y
     *
     * @return the value of t_pathology_info_detail.y
     *
     * @mbg.generated
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.y
     *
     * @param y the value for t_pathology_info_detail.y
     *
     * @mbg.generated
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.width
     *
     * @return the value of t_pathology_info_detail.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.width
     *
     * @param width the value for t_pathology_info_detail.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.height
     *
     * @return the value of t_pathology_info_detail.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.height
     *
     * @param height the value for t_pathology_info_detail.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.image_index
     *
     * @return the value of t_pathology_info_detail.image_index
     *
     * @mbg.generated
     */
    public Integer getImageIndex() {
        return imageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.image_index
     *
     * @param imageIndex the value for t_pathology_info_detail.image_index
     *
     * @mbg.generated
     */
    public void setImageIndex(Integer imageIndex) {
        this.imageIndex = imageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_info_detail.annotation_id
     *
     * @return the value of t_pathology_info_detail.annotation_id
     *
     * @mbg.generated
     */
    public Integer getAnnotationId() {
        return annotationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_info_detail.annotation_id
     *
     * @param annotationId the value for t_pathology_info_detail.annotation_id
     *
     * @mbg.generated
     */
    public void setAnnotationId(Integer annotationId) {
        this.annotationId = annotationId;
    }
}