package com.terrydr.domain.pathology;

import com.terrydr.domain.FatherBean;

import java.util.Date;

public class PathologyConsultation extends FatherBean{

    public PathologyConsultation(com.terrydr.domain.PathologyConsultation consultation) {
        this.id = consultation.getId();
        this.recordId = consultation.getRecordId();
        this.shareId = consultation.getShareId();
        this.consultationType = 2; //以前的会诊，均视为会诊
        this.createDoctorId = consultation.getCreateDoctorId();
        this.consultationDoctorId = consultation.getConsultationDoctorId();
        this.consultationDoctorName = consultation.getConsultationDoctorName();
        this.consultationDoctorTeleno = consultation.getConsultationDoctorTeleno();
        this.consultationDoctorAvatar = consultation.getConsultationDoctorAvatar();
        this.consultationHospitalId = consultation.getConsultationHospitalId();
        this.consultationHospitalName = consultation.getConsultationHospitalName();
        this.createTime = consultation.getCreateTime();
        this.endTime = consultation.getEndTime();
        this.status = consultation.getStatus();
        this.description = consultation.getDescription();
        this.closeUserType = consultation.getCloseUserType();
    }

    @Override
    public String toString() {
        return "Pathology_Consultation（ID=" + this.id + "）";
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_type
     *
     * @mbg.generated
     */
    private Integer consultationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.create_doctor_id
     *
     * @mbg.generated
     */
    private Integer createDoctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_doctor_id
     *
     * @mbg.generated
     */
    private Integer consultationDoctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_doctor_name
     *
     * @mbg.generated
     */
    private String consultationDoctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_doctor_teleno
     *
     * @mbg.generated
     */
    private String consultationDoctorTeleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_doctor_avatar
     *
     * @mbg.generated
     */
    private String consultationDoctorAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_hospital_id
     *
     * @mbg.generated
     */
    private Integer consultationHospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.consultation_hospital_name
     *
     * @mbg.generated
     */
    private String consultationHospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_consultation.close_user_type
     *
     * @mbg.generated
     */
    private String closeUserType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.id
     *
     * @return the value of t_consultation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.id
     *
     * @param id the value for t_consultation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.record_id
     *
     * @return the value of t_consultation.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.record_id
     *
     * @param recordId the value for t_consultation.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.share_id
     *
     * @return the value of t_consultation.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.share_id
     *
     * @param shareId the value for t_consultation.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId == null ? null : shareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_type
     *
     * @return the value of t_consultation.consultation_type
     *
     * @mbg.generated
     */
    public Integer getConsultationType() {
        return consultationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_type
     *
     * @param consultationType the value for t_consultation.consultation_type
     *
     * @mbg.generated
     */
    public void setConsultationType(Integer consultationType) {
        this.consultationType = consultationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.create_doctor_id
     *
     * @return the value of t_consultation.create_doctor_id
     *
     * @mbg.generated
     */
    public Integer getCreateDoctorId() {
        return createDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.create_doctor_id
     *
     * @param createDoctorId the value for t_consultation.create_doctor_id
     *
     * @mbg.generated
     */
    public void setCreateDoctorId(Integer createDoctorId) {
        this.createDoctorId = createDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_doctor_id
     *
     * @return the value of t_consultation.consultation_doctor_id
     *
     * @mbg.generated
     */
    public Integer getConsultationDoctorId() {
        return consultationDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_doctor_id
     *
     * @param consultationDoctorId the value for t_consultation.consultation_doctor_id
     *
     * @mbg.generated
     */
    public void setConsultationDoctorId(Integer consultationDoctorId) {
        this.consultationDoctorId = consultationDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_doctor_name
     *
     * @return the value of t_consultation.consultation_doctor_name
     *
     * @mbg.generated
     */
    public String getConsultationDoctorName() {
        return consultationDoctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_doctor_name
     *
     * @param consultationDoctorName the value for t_consultation.consultation_doctor_name
     *
     * @mbg.generated
     */
    public void setConsultationDoctorName(String consultationDoctorName) {
        this.consultationDoctorName = consultationDoctorName == null ? null : consultationDoctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_doctor_teleno
     *
     * @return the value of t_consultation.consultation_doctor_teleno
     *
     * @mbg.generated
     */
    public String getConsultationDoctorTeleno() {
        return consultationDoctorTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_doctor_teleno
     *
     * @param consultationDoctorTeleno the value for t_consultation.consultation_doctor_teleno
     *
     * @mbg.generated
     */
    public void setConsultationDoctorTeleno(String consultationDoctorTeleno) {
        this.consultationDoctorTeleno = consultationDoctorTeleno == null ? null : consultationDoctorTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_doctor_avatar
     *
     * @return the value of t_consultation.consultation_doctor_avatar
     *
     * @mbg.generated
     */
    public String getConsultationDoctorAvatar() {
        return consultationDoctorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_doctor_avatar
     *
     * @param consultationDoctorAvatar the value for t_consultation.consultation_doctor_avatar
     *
     * @mbg.generated
     */
    public void setConsultationDoctorAvatar(String consultationDoctorAvatar) {
        this.consultationDoctorAvatar = consultationDoctorAvatar == null ? null : consultationDoctorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_hospital_id
     *
     * @return the value of t_consultation.consultation_hospital_id
     *
     * @mbg.generated
     */
    public Integer getConsultationHospitalId() {
        return consultationHospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_hospital_id
     *
     * @param consultationHospitalId the value for t_consultation.consultation_hospital_id
     *
     * @mbg.generated
     */
    public void setConsultationHospitalId(Integer consultationHospitalId) {
        this.consultationHospitalId = consultationHospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.consultation_hospital_name
     *
     * @return the value of t_consultation.consultation_hospital_name
     *
     * @mbg.generated
     */
    public String getConsultationHospitalName() {
        return consultationHospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.consultation_hospital_name
     *
     * @param consultationHospitalName the value for t_consultation.consultation_hospital_name
     *
     * @mbg.generated
     */
    public void setConsultationHospitalName(String consultationHospitalName) {
        this.consultationHospitalName = consultationHospitalName == null ? null : consultationHospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.create_time
     *
     * @return the value of t_consultation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.create_time
     *
     * @param createTime the value for t_consultation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.end_time
     *
     * @return the value of t_consultation.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.end_time
     *
     * @param endTime the value for t_consultation.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.status
     *
     * @return the value of t_consultation.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.status
     *
     * @param status the value for t_consultation.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.description
     *
     * @return the value of t_consultation.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.description
     *
     * @param description the value for t_consultation.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_consultation.close_user_type
     *
     * @return the value of t_consultation.close_user_type
     *
     * @mbg.generated
     */
    public String getCloseUserType() {
        return closeUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_consultation.close_user_type
     *
     * @param closeUserType the value for t_consultation.close_user_type
     *
     * @mbg.generated
     */
    public void setCloseUserType(String closeUserType) {
        this.closeUserType = closeUserType == null ? null : closeUserType.trim();
    }
}