package com.terrydr.domain.pathology;

import com.terrydr.domain.ReportAttr;

public class PathologyReportAttr {

    public PathologyReportAttr(ReportAttr attr) {
        this.attrId = attr.getAttrId();
        this.reportType = attr.getReportType();
        this.attrNameE = attr.getAttrNameE();
        this.attrNameC = attr.getAttrNameC();
        this.attrUnit = attr.getAttrUnit();
        this.attrType = attr.getAttrType();
        this.attrNote = attr.getAttrNote();
        this.attrStatus = attr.getAttrStatus();
    }

    @Override
    public String toString() {
        return "Pathology_Report_Attr（Id=" + this.attrId + "）";
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_id
     *
     * @mbg.generated
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.report_type
     *
     * @mbg.generated
     */
    private Integer reportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_name_e
     *
     * @mbg.generated
     */
    private String attrNameE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_name_c
     *
     * @mbg.generated
     */
    private String attrNameC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_unit
     *
     * @mbg.generated
     */
    private String attrUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_type
     *
     * @mbg.generated
     */
    private String attrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_note
     *
     * @mbg.generated
     */
    private String attrNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_attr.attr_status
     *
     * @mbg.generated
     */
    private Integer attrStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_id
     *
     * @return the value of t_report_attr.attr_id
     *
     * @mbg.generated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_id
     *
     * @param attrId the value for t_report_attr.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.report_type
     *
     * @return the value of t_report_attr.report_type
     *
     * @mbg.generated
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.report_type
     *
     * @param reportType the value for t_report_attr.report_type
     *
     * @mbg.generated
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_name_e
     *
     * @return the value of t_report_attr.attr_name_e
     *
     * @mbg.generated
     */
    public String getAttrNameE() {
        return attrNameE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_name_e
     *
     * @param attrNameE the value for t_report_attr.attr_name_e
     *
     * @mbg.generated
     */
    public void setAttrNameE(String attrNameE) {
        this.attrNameE = attrNameE == null ? null : attrNameE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_name_c
     *
     * @return the value of t_report_attr.attr_name_c
     *
     * @mbg.generated
     */
    public String getAttrNameC() {
        return attrNameC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_name_c
     *
     * @param attrNameC the value for t_report_attr.attr_name_c
     *
     * @mbg.generated
     */
    public void setAttrNameC(String attrNameC) {
        this.attrNameC = attrNameC == null ? null : attrNameC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_unit
     *
     * @return the value of t_report_attr.attr_unit
     *
     * @mbg.generated
     */
    public String getAttrUnit() {
        return attrUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_unit
     *
     * @param attrUnit the value for t_report_attr.attr_unit
     *
     * @mbg.generated
     */
    public void setAttrUnit(String attrUnit) {
        this.attrUnit = attrUnit == null ? null : attrUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_type
     *
     * @return the value of t_report_attr.attr_type
     *
     * @mbg.generated
     */
    public String getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_type
     *
     * @param attrType the value for t_report_attr.attr_type
     *
     * @mbg.generated
     */
    public void setAttrType(String attrType) {
        this.attrType = attrType == null ? null : attrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_note
     *
     * @return the value of t_report_attr.attr_note
     *
     * @mbg.generated
     */
    public String getAttrNote() {
        return attrNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_note
     *
     * @param attrNote the value for t_report_attr.attr_note
     *
     * @mbg.generated
     */
    public void setAttrNote(String attrNote) {
        this.attrNote = attrNote == null ? null : attrNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_attr.attr_status
     *
     * @return the value of t_report_attr.attr_status
     *
     * @mbg.generated
     */
    public Integer getAttrStatus() {
        return attrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_attr.attr_status
     *
     * @param attrStatus the value for t_report_attr.attr_status
     *
     * @mbg.generated
     */
    public void setAttrStatus(Integer attrStatus) {
        this.attrStatus = attrStatus;
    }
}