package com.terrydr.domain;

import java.util.Date;

public class AIResult extends AIResultKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_result.detection_result
     *
     * @mbg.generated
     */
    private String detectionResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_result.detection_status
     *
     * @mbg.generated
     */
    private Integer detectionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_result.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_result.result_time
     *
     * @mbg.generated
     */
    private Date resultTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_result.detection_result
     *
     * @return the value of t_ai_result.detection_result
     *
     * @mbg.generated
     */
    public String getDetectionResult() {
        return detectionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_result.detection_result
     *
     * @param detectionResult the value for t_ai_result.detection_result
     *
     * @mbg.generated
     */
    public void setDetectionResult(String detectionResult) {
        this.detectionResult = detectionResult == null ? null : detectionResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_result.detection_status
     *
     * @return the value of t_ai_result.detection_status
     *
     * @mbg.generated
     */
    public Integer getDetectionStatus() {
        return detectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_result.detection_status
     *
     * @param detectionStatus the value for t_ai_result.detection_status
     *
     * @mbg.generated
     */
    public void setDetectionStatus(Integer detectionStatus) {
        this.detectionStatus = detectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_result.create_time
     *
     * @return the value of t_ai_result.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_result.create_time
     *
     * @param createTime the value for t_ai_result.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_result.result_time
     *
     * @return the value of t_ai_result.result_time
     *
     * @mbg.generated
     */
    public Date getResultTime() {
        return resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_result.result_time
     *
     * @param resultTime the value for t_ai_result.result_time
     *
     * @mbg.generated
     */
    public void setResultTime(Date resultTime) {
        this.resultTime = resultTime;
    }
}