package com.terrydr.domain;

import java.util.Date;

public class AITask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.record_type
     *
     * @mbg.generated
     */
    private Integer recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.detection_status
     *
     * @mbg.generated
     */
    private Integer detectionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.detection_type
     *
     * @mbg.generated
     */
    private Integer detectionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.detection_params
     *
     * @mbg.generated
     */
    private String detectionParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.detection_count
     *
     * @mbg.generated
     */
    private Integer detectionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.detection_result
     *
     * @mbg.generated
     */
    private String detectionResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ai_task.result_time
     *
     * @mbg.generated
     */
    private Date resultTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.id
     *
     * @return the value of t_ai_task.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.id
     *
     * @param id the value for t_ai_task.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.doctor_id
     *
     * @return the value of t_ai_task.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.doctor_id
     *
     * @param doctorId the value for t_ai_task.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.record_id
     *
     * @return the value of t_ai_task.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.record_id
     *
     * @param recordId the value for t_ai_task.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.record_type
     *
     * @return the value of t_ai_task.record_type
     *
     * @mbg.generated
     */
    public Integer getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.record_type
     *
     * @param recordType the value for t_ai_task.record_type
     *
     * @mbg.generated
     */
    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.detection_status
     *
     * @return the value of t_ai_task.detection_status
     *
     * @mbg.generated
     */
    public Integer getDetectionStatus() {
        return detectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.detection_status
     *
     * @param detectionStatus the value for t_ai_task.detection_status
     *
     * @mbg.generated
     */
    public void setDetectionStatus(Integer detectionStatus) {
        this.detectionStatus = detectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.detection_type
     *
     * @return the value of t_ai_task.detection_type
     *
     * @mbg.generated
     */
    public Integer getDetectionType() {
        return detectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.detection_type
     *
     * @param detectionType the value for t_ai_task.detection_type
     *
     * @mbg.generated
     */
    public void setDetectionType(Integer detectionType) {
        this.detectionType = detectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.detection_params
     *
     * @return the value of t_ai_task.detection_params
     *
     * @mbg.generated
     */
    public String getDetectionParams() {
        return detectionParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.detection_params
     *
     * @param detectionParams the value for t_ai_task.detection_params
     *
     * @mbg.generated
     */
    public void setDetectionParams(String detectionParams) {
        this.detectionParams = detectionParams == null ? null : detectionParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.detection_count
     *
     * @return the value of t_ai_task.detection_count
     *
     * @mbg.generated
     */
    public Integer getDetectionCount() {
        return detectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.detection_count
     *
     * @param detectionCount the value for t_ai_task.detection_count
     *
     * @mbg.generated
     */
    public void setDetectionCount(Integer detectionCount) {
        this.detectionCount = detectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.detection_result
     *
     * @return the value of t_ai_task.detection_result
     *
     * @mbg.generated
     */
    public String getDetectionResult() {
        return detectionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.detection_result
     *
     * @param detectionResult the value for t_ai_task.detection_result
     *
     * @mbg.generated
     */
    public void setDetectionResult(String detectionResult) {
        this.detectionResult = detectionResult == null ? null : detectionResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.create_time
     *
     * @return the value of t_ai_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.create_time
     *
     * @param createTime the value for t_ai_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ai_task.result_time
     *
     * @return the value of t_ai_task.result_time
     *
     * @mbg.generated
     */
    public Date getResultTime() {
        return resultTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ai_task.result_time
     *
     * @param resultTime the value for t_ai_task.result_time
     *
     * @mbg.generated
     */
    public void setResultTime(Date resultTime) {
        this.resultTime = resultTime;
    }
}