package com.terrydr.domain;

import java.util.Date;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
public class MedicalRecordValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.value_id
     *
     * @mbg.generated
     */
    private String valueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.attr_id
     *
     * @mbg.generated
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.record_type
     *
     * @mbg.generated
     */
    private Integer recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.attr_value
     *
     * @mbg.generated
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.value_time
     *
     * @mbg.generated
     */
    private Date valueTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.user_type
     *
     * @mbg.generated
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_value.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.value_id
     *
     * @return the value of t_medical_value.value_id
     *
     * @mbg.generated
     */
    public String getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.value_id
     *
     * @param valueId the value for t_medical_value.value_id
     *
     * @mbg.generated
     */
    public void setValueId(String valueId) {
        this.valueId = valueId == null ? null : valueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.attr_id
     *
     * @return the value of t_medical_value.attr_id
     *
     * @mbg.generated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.attr_id
     *
     * @param attrId the value for t_medical_value.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.record_id
     *
     * @return the value of t_medical_value.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.record_id
     *
     * @param recordId the value for t_medical_value.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.record_type
     *
     * @return the value of t_medical_value.record_type
     *
     * @mbg.generated
     */
    public Integer getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.record_type
     *
     * @param recordType the value for t_medical_value.record_type
     *
     * @mbg.generated
     */
    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.attr_value
     *
     * @return the value of t_medical_value.attr_value
     *
     * @mbg.generated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.attr_value
     *
     * @param attrValue the value for t_medical_value.attr_value
     *
     * @mbg.generated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.value_time
     *
     * @return the value of t_medical_value.value_time
     *
     * @mbg.generated
     */
    public Date getValueTime() {
        return valueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.value_time
     *
     * @param valueTime the value for t_medical_value.value_time
     *
     * @mbg.generated
     */
    public void setValueTime(Date valueTime) {
        this.valueTime = valueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.user_type
     *
     * @return the value of t_medical_value.user_type
     *
     * @mbg.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.user_type
     *
     * @param userType the value for t_medical_value.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_value.user_id
     *
     * @return the value of t_medical_value.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_value.user_id
     *
     * @param userId the value for t_medical_value.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}