package com.terrydr.domain;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
public class MedicalRecordAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_id
     *
     * @mbg.generated
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_level
     *
     * @mbg.generated
     */
    private Integer attrLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.record_type
     *
     * @mbg.generated
     */
    private Integer recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_name_e
     *
     * @mbg.generated
     */
    private String attrNameE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_name_c
     *
     * @mbg.generated
     */
    private String attrNameC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_unit
     *
     * @mbg.generated
     */
    private String attrUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_type
     *
     * @mbg.generated
     */
    private Integer attrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_note
     *
     * @mbg.generated
     */
    private String attrNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_sort
     *
     * @mbg.generated
     */
    private Integer attrSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_status
     *
     * @mbg.generated
     */
    private Integer attrStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_attr.attr_show
     *
     * @mbg.generated
     */
    private String attrShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_id
     *
     * @return the value of t_medical_attr.attr_id
     *
     * @mbg.generated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_id
     *
     * @param attrId the value for t_medical_attr.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.parent_id
     *
     * @return the value of t_medical_attr.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.parent_id
     *
     * @param parentId the value for t_medical_attr.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_level
     *
     * @return the value of t_medical_attr.attr_level
     *
     * @mbg.generated
     */
    public Integer getAttrLevel() {
        return attrLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_level
     *
     * @param attrLevel the value for t_medical_attr.attr_level
     *
     * @mbg.generated
     */
    public void setAttrLevel(Integer attrLevel) {
        this.attrLevel = attrLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.record_type
     *
     * @return the value of t_medical_attr.record_type
     *
     * @mbg.generated
     */
    public Integer getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.record_type
     *
     * @param recordType the value for t_medical_attr.record_type
     *
     * @mbg.generated
     */
    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_name_e
     *
     * @return the value of t_medical_attr.attr_name_e
     *
     * @mbg.generated
     */
    public String getAttrNameE() {
        return attrNameE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_name_e
     *
     * @param attrNameE the value for t_medical_attr.attr_name_e
     *
     * @mbg.generated
     */
    public void setAttrNameE(String attrNameE) {
        this.attrNameE = attrNameE == null ? null : attrNameE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_name_c
     *
     * @return the value of t_medical_attr.attr_name_c
     *
     * @mbg.generated
     */
    public String getAttrNameC() {
        return attrNameC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_name_c
     *
     * @param attrNameC the value for t_medical_attr.attr_name_c
     *
     * @mbg.generated
     */
    public void setAttrNameC(String attrNameC) {
        this.attrNameC = attrNameC == null ? null : attrNameC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_unit
     *
     * @return the value of t_medical_attr.attr_unit
     *
     * @mbg.generated
     */
    public String getAttrUnit() {
        return attrUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_unit
     *
     * @param attrUnit the value for t_medical_attr.attr_unit
     *
     * @mbg.generated
     */
    public void setAttrUnit(String attrUnit) {
        this.attrUnit = attrUnit == null ? null : attrUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_type
     *
     * @return the value of t_medical_attr.attr_type
     *
     * @mbg.generated
     */
    public Integer getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_type
     *
     * @param attrType the value for t_medical_attr.attr_type
     *
     * @mbg.generated
     */
    public void setAttrType(Integer attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_note
     *
     * @return the value of t_medical_attr.attr_note
     *
     * @mbg.generated
     */
    public String getAttrNote() {
        return attrNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_note
     *
     * @param attrNote the value for t_medical_attr.attr_note
     *
     * @mbg.generated
     */
    public void setAttrNote(String attrNote) {
        this.attrNote = attrNote == null ? null : attrNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_sort
     *
     * @return the value of t_medical_attr.attr_sort
     *
     * @mbg.generated
     */
    public Integer getAttrSort() {
        return attrSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_sort
     *
     * @param attrSort the value for t_medical_attr.attr_sort
     *
     * @mbg.generated
     */
    public void setAttrSort(Integer attrSort) {
        this.attrSort = attrSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_status
     *
     * @return the value of t_medical_attr.attr_status
     *
     * @mbg.generated
     */
    public Integer getAttrStatus() {
        return attrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_status
     *
     * @param attrStatus the value for t_medical_attr.attr_status
     *
     * @mbg.generated
     */
    public void setAttrStatus(Integer attrStatus) {
        this.attrStatus = attrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_attr.attr_show
     *
     * @return the value of t_medical_attr.attr_show
     *
     * @mbg.generated
     */
    public String getAttrShow() {
        return attrShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_attr.attr_show
     *
     * @param attrShow the value for t_medical_attr.attr_show
     *
     * @mbg.generated
     */
    public void setAttrShow(String attrShow) {
        this.attrShow = attrShow == null ? null : attrShow.trim();
    }
}