package com.terrydr.domain;

import java.util.Date;

public class PathologyAnnotation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.consultation_id
     *
     * @mbg.generated
     */
    private Integer consultationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.pathology_mark
     *
     * @mbg.generated
     */
    private String pathologyMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.scan_rate
     *
     * @mbg.generated
     */
    private Integer scanRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.x
     *
     * @mbg.generated
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.y
     *
     * @mbg.generated
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.create_doctor_id
     *
     * @mbg.generated
     */
    private Integer createDoctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pathology_annotation.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.id
     *
     * @return the value of t_pathology_annotation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.id
     *
     * @param id the value for t_pathology_annotation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.consultation_id
     *
     * @return the value of t_pathology_annotation.consultation_id
     *
     * @mbg.generated
     */
    public Integer getConsultationId() {
        return consultationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.consultation_id
     *
     * @param consultationId the value for t_pathology_annotation.consultation_id
     *
     * @mbg.generated
     */
    public void setConsultationId(Integer consultationId) {
        this.consultationId = consultationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.record_id
     *
     * @return the value of t_pathology_annotation.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.record_id
     *
     * @param recordId the value for t_pathology_annotation.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.share_id
     *
     * @return the value of t_pathology_annotation.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.share_id
     *
     * @param shareId the value for t_pathology_annotation.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId == null ? null : shareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.pathology_mark
     *
     * @return the value of t_pathology_annotation.pathology_mark
     *
     * @mbg.generated
     */
    public String getPathologyMark() {
        return pathologyMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.pathology_mark
     *
     * @param pathologyMark the value for t_pathology_annotation.pathology_mark
     *
     * @mbg.generated
     */
    public void setPathologyMark(String pathologyMark) {
        this.pathologyMark = pathologyMark == null ? null : pathologyMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.scan_rate
     *
     * @return the value of t_pathology_annotation.scan_rate
     *
     * @mbg.generated
     */
    public Integer getScanRate() {
        return scanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.scan_rate
     *
     * @param scanRate the value for t_pathology_annotation.scan_rate
     *
     * @mbg.generated
     */
    public void setScanRate(Integer scanRate) {
        this.scanRate = scanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.x
     *
     * @return the value of t_pathology_annotation.x
     *
     * @mbg.generated
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.x
     *
     * @param x the value for t_pathology_annotation.x
     *
     * @mbg.generated
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.y
     *
     * @return the value of t_pathology_annotation.y
     *
     * @mbg.generated
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.y
     *
     * @param y the value for t_pathology_annotation.y
     *
     * @mbg.generated
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.width
     *
     * @return the value of t_pathology_annotation.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.width
     *
     * @param width the value for t_pathology_annotation.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.height
     *
     * @return the value of t_pathology_annotation.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.height
     *
     * @param height the value for t_pathology_annotation.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.create_doctor_id
     *
     * @return the value of t_pathology_annotation.create_doctor_id
     *
     * @mbg.generated
     */
    public Integer getCreateDoctorId() {
        return createDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.create_doctor_id
     *
     * @param createDoctorId the value for t_pathology_annotation.create_doctor_id
     *
     * @mbg.generated
     */
    public void setCreateDoctorId(Integer createDoctorId) {
        this.createDoctorId = createDoctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.create_time
     *
     * @return the value of t_pathology_annotation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.create_time
     *
     * @param createTime the value for t_pathology_annotation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.status
     *
     * @return the value of t_pathology_annotation.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.status
     *
     * @param status the value for t_pathology_annotation.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pathology_annotation.is_delete
     *
     * @return the value of t_pathology_annotation.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pathology_annotation.is_delete
     *
     * @param isDelete the value for t_pathology_annotation.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}