package com.terrydr.dao.ecg;

import com.terrydr.domain.ecg.ECGMedicalRecord;
import org.springframework.stereotype.Repository;

@Repository
public interface ECGMedicalRecordDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recordId);

    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int insert(ECGMedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int insertSelective(ECGMedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    ECGMedicalRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ECGMedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ECGMedicalRecord record);
}