package com.terrydr.domain.eye;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.encrypt_id
     *
     * @mbg.generated
     */
    private String encryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.teleno
     *
     * @mbg.generated
     */
    private String teleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_prov_id
     *
     * @mbg.generated
     */
    private String lpProvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_prov_name
     *
     * @mbg.generated
     */
    private String lpProvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_city_id
     *
     * @mbg.generated
     */
    private String lpCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_city_name
     *
     * @mbg.generated
     */
    private String lpCityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_area_id
     *
     * @mbg.generated
     */
    private String lpAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.lp_area_name
     *
     * @mbg.generated
     */
    private String lpAreaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.live_place
     *
     * @mbg.generated
     */
    private String livePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_prov_id
     *
     * @mbg.generated
     */
    private String hrProvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_prov_name
     *
     * @mbg.generated
     */
    private String hrProvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_city_id
     *
     * @mbg.generated
     */
    private String hrCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_city_name
     *
     * @mbg.generated
     */
    private String hrCityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_area_id
     *
     * @mbg.generated
     */
    private String hrAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hr_area_name
     *
     * @mbg.generated
     */
    private String hrAreaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.household_register
     *
     * @mbg.generated
     */
    private String householdRegister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.medical_card_type
     *
     * @mbg.generated
     */
    private Integer medicalCardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.medical_card_id
     *
     * @mbg.generated
     */
    private String medicalCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.nation_id
     *
     * @mbg.generated
     */
    private Integer nationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.nation_name
     *
     * @mbg.generated
     */
    private String nationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.occupation
     *
     * @mbg.generated
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.employment_situation
     *
     * @mbg.generated
     */
    private String employmentSituation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.education_levels
     *
     * @mbg.generated
     */
    private Integer educationLevels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.marital_status
     *
     * @mbg.generated
     */
    private Integer maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.patient_id
     *
     * @mbg.generated
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.is_diabetes
     *
     * @mbg.generated
     */
    private Integer isDiabetes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.diabetes_diagnosis_date
     *
     * @mbg.generated
     */
    private Date diabetesDiagnosisDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.diabetes_status
     *
     * @mbg.generated
     */
    private Integer diabetesStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.is_hypertension
     *
     * @mbg.generated
     */
    private Integer isHypertension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hypertension_diagnosis_date
     *
     * @mbg.generated
     */
    private Date hypertensionDiagnosisDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.hypertension_status
     *
     * @mbg.generated
     */
    private Integer hypertensionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.diseases_other
     *
     * @mbg.generated
     */
    private String diseasesOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.oculo_is_glaucoma
     *
     * @mbg.generated
     */
    private Integer oculoIsGlaucoma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.oculo_is_dr
     *
     * @mbg.generated
     */
    private Integer oculoIsDr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.oculo_other
     *
     * @mbg.generated
     */
    private String oculoOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.family_is_glaucoma
     *
     * @mbg.generated
     */
    private Integer familyIsGlaucoma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.family_is_hypertension
     *
     * @mbg.generated
     */
    private Integer familyIsHypertension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.family_other
     *
     * @mbg.generated
     */
    private String familyOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.smoke
     *
     * @mbg.generated
     */
    private String smoke;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.drink
     *
     * @mbg.generated
     */
    private String drink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sport
     *
     * @mbg.generated
     */
    private String sport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.electr_time
     *
     * @mbg.generated
     */
    private String electrTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.encrypt_id
     *
     * @return the value of t_customer.encrypt_id
     *
     * @mbg.generated
     */
    public String getEncryptId() {
        return encryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.encrypt_id
     *
     * @param encryptId the value for t_customer.encrypt_id
     *
     * @mbg.generated
     */
    public void setEncryptId(String encryptId) {
        this.encryptId = encryptId == null ? null : encryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.birthday
     *
     * @return the value of t_customer.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.birthday
     *
     * @param birthday the value for t_customer.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.teleno
     *
     * @return the value of t_customer.teleno
     *
     * @mbg.generated
     */
    public String getTeleno() {
        return teleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.teleno
     *
     * @param teleno the value for t_customer.teleno
     *
     * @mbg.generated
     */
    public void setTeleno(String teleno) {
        this.teleno = teleno == null ? null : teleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id_card
     *
     * @return the value of t_customer.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id_card
     *
     * @param idCard the value for t_customer.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_prov_id
     *
     * @return the value of t_customer.lp_prov_id
     *
     * @mbg.generated
     */
    public String getLpProvId() {
        return lpProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_prov_id
     *
     * @param lpProvId the value for t_customer.lp_prov_id
     *
     * @mbg.generated
     */
    public void setLpProvId(String lpProvId) {
        this.lpProvId = lpProvId == null ? null : lpProvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_prov_name
     *
     * @return the value of t_customer.lp_prov_name
     *
     * @mbg.generated
     */
    public String getLpProvName() {
        return lpProvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_prov_name
     *
     * @param lpProvName the value for t_customer.lp_prov_name
     *
     * @mbg.generated
     */
    public void setLpProvName(String lpProvName) {
        this.lpProvName = lpProvName == null ? null : lpProvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_city_id
     *
     * @return the value of t_customer.lp_city_id
     *
     * @mbg.generated
     */
    public String getLpCityId() {
        return lpCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_city_id
     *
     * @param lpCityId the value for t_customer.lp_city_id
     *
     * @mbg.generated
     */
    public void setLpCityId(String lpCityId) {
        this.lpCityId = lpCityId == null ? null : lpCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_city_name
     *
     * @return the value of t_customer.lp_city_name
     *
     * @mbg.generated
     */
    public String getLpCityName() {
        return lpCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_city_name
     *
     * @param lpCityName the value for t_customer.lp_city_name
     *
     * @mbg.generated
     */
    public void setLpCityName(String lpCityName) {
        this.lpCityName = lpCityName == null ? null : lpCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_area_id
     *
     * @return the value of t_customer.lp_area_id
     *
     * @mbg.generated
     */
    public String getLpAreaId() {
        return lpAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_area_id
     *
     * @param lpAreaId the value for t_customer.lp_area_id
     *
     * @mbg.generated
     */
    public void setLpAreaId(String lpAreaId) {
        this.lpAreaId = lpAreaId == null ? null : lpAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.lp_area_name
     *
     * @return the value of t_customer.lp_area_name
     *
     * @mbg.generated
     */
    public String getLpAreaName() {
        return lpAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.lp_area_name
     *
     * @param lpAreaName the value for t_customer.lp_area_name
     *
     * @mbg.generated
     */
    public void setLpAreaName(String lpAreaName) {
        this.lpAreaName = lpAreaName == null ? null : lpAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.live_place
     *
     * @return the value of t_customer.live_place
     *
     * @mbg.generated
     */
    public String getLivePlace() {
        return livePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.live_place
     *
     * @param livePlace the value for t_customer.live_place
     *
     * @mbg.generated
     */
    public void setLivePlace(String livePlace) {
        this.livePlace = livePlace == null ? null : livePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_prov_id
     *
     * @return the value of t_customer.hr_prov_id
     *
     * @mbg.generated
     */
    public String getHrProvId() {
        return hrProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_prov_id
     *
     * @param hrProvId the value for t_customer.hr_prov_id
     *
     * @mbg.generated
     */
    public void setHrProvId(String hrProvId) {
        this.hrProvId = hrProvId == null ? null : hrProvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_prov_name
     *
     * @return the value of t_customer.hr_prov_name
     *
     * @mbg.generated
     */
    public String getHrProvName() {
        return hrProvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_prov_name
     *
     * @param hrProvName the value for t_customer.hr_prov_name
     *
     * @mbg.generated
     */
    public void setHrProvName(String hrProvName) {
        this.hrProvName = hrProvName == null ? null : hrProvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_city_id
     *
     * @return the value of t_customer.hr_city_id
     *
     * @mbg.generated
     */
    public String getHrCityId() {
        return hrCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_city_id
     *
     * @param hrCityId the value for t_customer.hr_city_id
     *
     * @mbg.generated
     */
    public void setHrCityId(String hrCityId) {
        this.hrCityId = hrCityId == null ? null : hrCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_city_name
     *
     * @return the value of t_customer.hr_city_name
     *
     * @mbg.generated
     */
    public String getHrCityName() {
        return hrCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_city_name
     *
     * @param hrCityName the value for t_customer.hr_city_name
     *
     * @mbg.generated
     */
    public void setHrCityName(String hrCityName) {
        this.hrCityName = hrCityName == null ? null : hrCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_area_id
     *
     * @return the value of t_customer.hr_area_id
     *
     * @mbg.generated
     */
    public String getHrAreaId() {
        return hrAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_area_id
     *
     * @param hrAreaId the value for t_customer.hr_area_id
     *
     * @mbg.generated
     */
    public void setHrAreaId(String hrAreaId) {
        this.hrAreaId = hrAreaId == null ? null : hrAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hr_area_name
     *
     * @return the value of t_customer.hr_area_name
     *
     * @mbg.generated
     */
    public String getHrAreaName() {
        return hrAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hr_area_name
     *
     * @param hrAreaName the value for t_customer.hr_area_name
     *
     * @mbg.generated
     */
    public void setHrAreaName(String hrAreaName) {
        this.hrAreaName = hrAreaName == null ? null : hrAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.household_register
     *
     * @return the value of t_customer.household_register
     *
     * @mbg.generated
     */
    public String getHouseholdRegister() {
        return householdRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.household_register
     *
     * @param householdRegister the value for t_customer.household_register
     *
     * @mbg.generated
     */
    public void setHouseholdRegister(String householdRegister) {
        this.householdRegister = householdRegister == null ? null : householdRegister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.medical_card_type
     *
     * @return the value of t_customer.medical_card_type
     *
     * @mbg.generated
     */
    public Integer getMedicalCardType() {
        return medicalCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.medical_card_type
     *
     * @param medicalCardType the value for t_customer.medical_card_type
     *
     * @mbg.generated
     */
    public void setMedicalCardType(Integer medicalCardType) {
        this.medicalCardType = medicalCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.medical_card_id
     *
     * @return the value of t_customer.medical_card_id
     *
     * @mbg.generated
     */
    public String getMedicalCardId() {
        return medicalCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.medical_card_id
     *
     * @param medicalCardId the value for t_customer.medical_card_id
     *
     * @mbg.generated
     */
    public void setMedicalCardId(String medicalCardId) {
        this.medicalCardId = medicalCardId == null ? null : medicalCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.nation_id
     *
     * @return the value of t_customer.nation_id
     *
     * @mbg.generated
     */
    public Integer getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.nation_id
     *
     * @param nationId the value for t_customer.nation_id
     *
     * @mbg.generated
     */
    public void setNationId(Integer nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.nation_name
     *
     * @return the value of t_customer.nation_name
     *
     * @mbg.generated
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.nation_name
     *
     * @param nationName the value for t_customer.nation_name
     *
     * @mbg.generated
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.occupation
     *
     * @return the value of t_customer.occupation
     *
     * @mbg.generated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.occupation
     *
     * @param occupation the value for t_customer.occupation
     *
     * @mbg.generated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.employment_situation
     *
     * @return the value of t_customer.employment_situation
     *
     * @mbg.generated
     */
    public String getEmploymentSituation() {
        return employmentSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.employment_situation
     *
     * @param employmentSituation the value for t_customer.employment_situation
     *
     * @mbg.generated
     */
    public void setEmploymentSituation(String employmentSituation) {
        this.employmentSituation = employmentSituation == null ? null : employmentSituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.education_levels
     *
     * @return the value of t_customer.education_levels
     *
     * @mbg.generated
     */
    public Integer getEducationLevels() {
        return educationLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.education_levels
     *
     * @param educationLevels the value for t_customer.education_levels
     *
     * @mbg.generated
     */
    public void setEducationLevels(Integer educationLevels) {
        this.educationLevels = educationLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.marital_status
     *
     * @return the value of t_customer.marital_status
     *
     * @mbg.generated
     */
    public Integer getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.marital_status
     *
     * @param maritalStatus the value for t_customer.marital_status
     *
     * @mbg.generated
     */
    public void setMaritalStatus(Integer maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.doctor_id
     *
     * @return the value of t_customer.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.doctor_id
     *
     * @param doctorId the value for t_customer.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.doctor_name
     *
     * @return the value of t_customer.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.doctor_name
     *
     * @param doctorName the value for t_customer.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hospital_id
     *
     * @return the value of t_customer.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hospital_id
     *
     * @param hospitalId the value for t_customer.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hospital_name
     *
     * @return the value of t_customer.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hospital_name
     *
     * @param hospitalName the value for t_customer.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_time
     *
     * @return the value of t_customer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_time
     *
     * @param createTime the value for t_customer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.patient_id
     *
     * @return the value of t_customer.patient_id
     *
     * @mbg.generated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.patient_id
     *
     * @param patientId the value for t_customer.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.is_diabetes
     *
     * @return the value of t_customer.is_diabetes
     *
     * @mbg.generated
     */
    public Integer getIsDiabetes() {
        return isDiabetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.is_diabetes
     *
     * @param isDiabetes the value for t_customer.is_diabetes
     *
     * @mbg.generated
     */
    public void setIsDiabetes(Integer isDiabetes) {
        this.isDiabetes = isDiabetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.diabetes_diagnosis_date
     *
     * @return the value of t_customer.diabetes_diagnosis_date
     *
     * @mbg.generated
     */
    public Date getDiabetesDiagnosisDate() {
        return diabetesDiagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.diabetes_diagnosis_date
     *
     * @param diabetesDiagnosisDate the value for t_customer.diabetes_diagnosis_date
     *
     * @mbg.generated
     */
    public void setDiabetesDiagnosisDate(Date diabetesDiagnosisDate) {
        this.diabetesDiagnosisDate = diabetesDiagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.diabetes_status
     *
     * @return the value of t_customer.diabetes_status
     *
     * @mbg.generated
     */
    public Integer getDiabetesStatus() {
        return diabetesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.diabetes_status
     *
     * @param diabetesStatus the value for t_customer.diabetes_status
     *
     * @mbg.generated
     */
    public void setDiabetesStatus(Integer diabetesStatus) {
        this.diabetesStatus = diabetesStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.is_hypertension
     *
     * @return the value of t_customer.is_hypertension
     *
     * @mbg.generated
     */
    public Integer getIsHypertension() {
        return isHypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.is_hypertension
     *
     * @param isHypertension the value for t_customer.is_hypertension
     *
     * @mbg.generated
     */
    public void setIsHypertension(Integer isHypertension) {
        this.isHypertension = isHypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hypertension_diagnosis_date
     *
     * @return the value of t_customer.hypertension_diagnosis_date
     *
     * @mbg.generated
     */
    public Date getHypertensionDiagnosisDate() {
        return hypertensionDiagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hypertension_diagnosis_date
     *
     * @param hypertensionDiagnosisDate the value for t_customer.hypertension_diagnosis_date
     *
     * @mbg.generated
     */
    public void setHypertensionDiagnosisDate(Date hypertensionDiagnosisDate) {
        this.hypertensionDiagnosisDate = hypertensionDiagnosisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.hypertension_status
     *
     * @return the value of t_customer.hypertension_status
     *
     * @mbg.generated
     */
    public Integer getHypertensionStatus() {
        return hypertensionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.hypertension_status
     *
     * @param hypertensionStatus the value for t_customer.hypertension_status
     *
     * @mbg.generated
     */
    public void setHypertensionStatus(Integer hypertensionStatus) {
        this.hypertensionStatus = hypertensionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.diseases_other
     *
     * @return the value of t_customer.diseases_other
     *
     * @mbg.generated
     */
    public String getDiseasesOther() {
        return diseasesOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.diseases_other
     *
     * @param diseasesOther the value for t_customer.diseases_other
     *
     * @mbg.generated
     */
    public void setDiseasesOther(String diseasesOther) {
        this.diseasesOther = diseasesOther == null ? null : diseasesOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.oculo_is_glaucoma
     *
     * @return the value of t_customer.oculo_is_glaucoma
     *
     * @mbg.generated
     */
    public Integer getOculoIsGlaucoma() {
        return oculoIsGlaucoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.oculo_is_glaucoma
     *
     * @param oculoIsGlaucoma the value for t_customer.oculo_is_glaucoma
     *
     * @mbg.generated
     */
    public void setOculoIsGlaucoma(Integer oculoIsGlaucoma) {
        this.oculoIsGlaucoma = oculoIsGlaucoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.oculo_is_dr
     *
     * @return the value of t_customer.oculo_is_dr
     *
     * @mbg.generated
     */
    public Integer getOculoIsDr() {
        return oculoIsDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.oculo_is_dr
     *
     * @param oculoIsDr the value for t_customer.oculo_is_dr
     *
     * @mbg.generated
     */
    public void setOculoIsDr(Integer oculoIsDr) {
        this.oculoIsDr = oculoIsDr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.oculo_other
     *
     * @return the value of t_customer.oculo_other
     *
     * @mbg.generated
     */
    public String getOculoOther() {
        return oculoOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.oculo_other
     *
     * @param oculoOther the value for t_customer.oculo_other
     *
     * @mbg.generated
     */
    public void setOculoOther(String oculoOther) {
        this.oculoOther = oculoOther == null ? null : oculoOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.family_is_glaucoma
     *
     * @return the value of t_customer.family_is_glaucoma
     *
     * @mbg.generated
     */
    public Integer getFamilyIsGlaucoma() {
        return familyIsGlaucoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.family_is_glaucoma
     *
     * @param familyIsGlaucoma the value for t_customer.family_is_glaucoma
     *
     * @mbg.generated
     */
    public void setFamilyIsGlaucoma(Integer familyIsGlaucoma) {
        this.familyIsGlaucoma = familyIsGlaucoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.family_is_hypertension
     *
     * @return the value of t_customer.family_is_hypertension
     *
     * @mbg.generated
     */
    public Integer getFamilyIsHypertension() {
        return familyIsHypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.family_is_hypertension
     *
     * @param familyIsHypertension the value for t_customer.family_is_hypertension
     *
     * @mbg.generated
     */
    public void setFamilyIsHypertension(Integer familyIsHypertension) {
        this.familyIsHypertension = familyIsHypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.family_other
     *
     * @return the value of t_customer.family_other
     *
     * @mbg.generated
     */
    public String getFamilyOther() {
        return familyOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.family_other
     *
     * @param familyOther the value for t_customer.family_other
     *
     * @mbg.generated
     */
    public void setFamilyOther(String familyOther) {
        this.familyOther = familyOther == null ? null : familyOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.smoke
     *
     * @return the value of t_customer.smoke
     *
     * @mbg.generated
     */
    public String getSmoke() {
        return smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.smoke
     *
     * @param smoke the value for t_customer.smoke
     *
     * @mbg.generated
     */
    public void setSmoke(String smoke) {
        this.smoke = smoke == null ? null : smoke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.drink
     *
     * @return the value of t_customer.drink
     *
     * @mbg.generated
     */
    public String getDrink() {
        return drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.drink
     *
     * @param drink the value for t_customer.drink
     *
     * @mbg.generated
     */
    public void setDrink(String drink) {
        this.drink = drink == null ? null : drink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sport
     *
     * @return the value of t_customer.sport
     *
     * @mbg.generated
     */
    public String getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sport
     *
     * @param sport the value for t_customer.sport
     *
     * @mbg.generated
     */
    public void setSport(String sport) {
        this.sport = sport == null ? null : sport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.electr_time
     *
     * @return the value of t_customer.electr_time
     *
     * @mbg.generated
     */
    public String getElectrTime() {
        return electrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.electr_time
     *
     * @param electrTime the value for t_customer.electr_time
     *
     * @mbg.generated
     */
    public void setElectrTime(String electrTime) {
        this.electrTime = electrTime == null ? null : electrTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.last_update_time
     *
     * @return the value of t_customer.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.last_update_time
     *
     * @param lastUpdateTime the value for t_customer.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.is_delete
     *
     * @return the value of t_customer.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.is_delete
     *
     * @param isDelete the value for t_customer.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}