package com.terrydr.domain.eye;

import java.util.Date;

/**
 * Copyright (C), 2018-2020, NanJing Terrydr. Co., Ltd.
 *
 * @Package: com.terrydr.domain.eye
 * @Description: ${TODO}
 * @author: YanZhengYuan
 * @Date: 2018/5/28 16:38
 * @version: 1.00
 */
public class Detail {

    private Date patientBirthday;
    private String patientAvatar;
    private Integer patientStatus;
    private Date patientRegistTime;
    private Integer patientCreatedDid;
    private String patientCreatedDName;
    private Integer patientCreatedHid;
    private String patientCreatedHName;
    private String c3Name;
    private Integer c3Id;
    private String c2Name;
    private Integer c2Id;
    private String c1Name;
    private Integer c1Id;
    private String rpt;
    private String rpa;
    private String rpn;
    private Integer rps;

    public String getRpt() {
        return rpt;
    }

    public void setRpt(String rpt) {
        this.rpt = rpt;
    }

    public String getRpa() {
        return rpa;
    }

    public void setRpa(String rpa) {
        this.rpa = rpa;
    }

    public String getRpn() {
        return rpn;
    }

    public void setRpn(String rpn) {
        this.rpn = rpn;
    }

    public Integer getRps() {
        return rps;
    }

    public void setRps(Integer rps) {
        this.rps = rps;
    }

    public Date getPatientBirthday() {
        return patientBirthday;
    }

    public void setPatientBirthday(Date patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    public String getPatientAvatar() {
        return patientAvatar;
    }

    public void setPatientAvatar(String patientAvatar) {
        this.patientAvatar = patientAvatar;
    }

    public Integer getPatientStatus() {
        return patientStatus;
    }

    public void setPatientStatus(Integer patientStatus) {
        this.patientStatus = patientStatus;
    }

    public Date getPatientRegistTime() {
        return patientRegistTime;
    }

    public void setPatientRegistTime(Date patientRegistTime) {
        this.patientRegistTime = patientRegistTime;
    }

    public Integer getPatientCreatedDid() {
        return patientCreatedDid;
    }

    public void setPatientCreatedDid(Integer patientCreatedDid) {
        this.patientCreatedDid = patientCreatedDid;
    }

    public String getPatientCreatedDName() {
        return patientCreatedDName;
    }

    public void setPatientCreatedDName(String patientCreatedDName) {
        this.patientCreatedDName = patientCreatedDName;
    }

    public Integer getPatientCreatedHid() {
        return patientCreatedHid;
    }

    public void setPatientCreatedHid(Integer patientCreatedHid) {
        this.patientCreatedHid = patientCreatedHid;
    }

    public String getPatientCreatedHName() {
        return patientCreatedHName;
    }

    public void setPatientCreatedHName(String patientCreatedHName) {
        this.patientCreatedHName = patientCreatedHName;
    }

    public String getC3Name() {
        return c3Name;
    }

    public void setC3Name(String c3Name) {
        this.c3Name = c3Name;
    }

    public Integer getC3Id() {
        return c3Id;
    }

    public void setC3Id(Integer c3Id) {
        this.c3Id = c3Id;
    }

    public String getC2Name() {
        return c2Name;
    }

    public void setC2Name(String c2Name) {
        this.c2Name = c2Name;
    }

    public Integer getC2Id() {
        return c2Id;
    }

    public void setC2Id(Integer c2Id) {
        this.c2Id = c2Id;
    }

    public String getC1Name() {
        return c1Name;
    }

    public void setC1Name(String c1Name) {
        this.c1Name = c1Name;
    }

    public Integer getC1Id() {
        return c1Id;
    }

    public void setC1Id(Integer c1Id) {
        this.c1Id = c1Id;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_id
     *
     * @mbg.generated
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_teleno
     *
     * @mbg.generated
     */
    private String patientTeleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_name
     *
     * @mbg.generated
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_age
     *
     * @mbg.generated
     */
    private String patientAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_sex
     *
     * @mbg.generated
     */
    private Integer patientSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_teleno
     *
     * @mbg.generated
     */
    private String doctorTeleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_avatar
     *
     * @mbg.generated
     */
    private String doctorAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_cover
     *
     * @mbg.generated
     */
    private String medicalCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_no
     *
     * @mbg.generated
     */
    private String patientNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.admission_no
     *
     * @mbg.generated
     */
    private String admissionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.bed_no
     *
     * @mbg.generated
     */
    private String bedNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.record_no
     *
     * @mbg.generated
     */
    private String recordNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_date
     *
     * @mbg.generated
     */
    private Date medicalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_conclusion
     *
     * @mbg.generated
     */
    private String medicalConclusion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_pictures
     *
     * @mbg.generated
     */
    private String medicalPictures;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_video
     *
     * @mbg.generated
     */
    private String medicalVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_code
     *
     * @mbg.generated
     */
    private String medicalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_left_vision
     *
     * @mbg.generated
     */
    private String eyeLeftVision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_right_vision
     *
     * @mbg.generated
     */
    private String eyeRightVision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_left_img
     *
     * @mbg.generated
     */
    private String eyeLeftImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_right_img
     *
     * @mbg.generated
     */
    private String eyeRightImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_left_video
     *
     * @mbg.generated
     */
    private String eyeLeftVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.eye_right_video
     *
     * @mbg.generated
     */
    private String eyeRightVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.report_status
     *
     * @mbg.generated
     */
    private Integer reportStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.client_type
     *
     * @mbg.generated
     */
    private Integer clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_enterprise
     *
     * @mbg.generated
     */
    private Integer isEnterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_remote
     *
     * @mbg.generated
     */
    private Integer isRemote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_base
     *
     * @mbg.generated
     */
    private Integer isBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.record_id
     *
     * @return the value of t_medical_record.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.record_id
     *
     * @param recordId the value for t_medical_record.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.share_id
     *
     * @return the value of t_medical_record.share_id
     *
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.share_id
     *
     * @param shareId the value for t_medical_record.share_id
     *
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId == null ? null : shareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.type
     *
     * @return the value of t_medical_record.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.type
     *
     * @param type the value for t_medical_record.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_id
     *
     * @return the value of t_medical_record.patient_id
     *
     * @mbg.generated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_id
     *
     * @param patientId the value for t_medical_record.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_teleno
     *
     * @return the value of t_medical_record.patient_teleno
     *
     * @mbg.generated
     */
    public String getPatientTeleno() {
        return patientTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_teleno
     *
     * @param patientTeleno the value for t_medical_record.patient_teleno
     *
     * @mbg.generated
     */
    public void setPatientTeleno(String patientTeleno) {
        this.patientTeleno = patientTeleno == null ? null : patientTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_name
     *
     * @return the value of t_medical_record.patient_name
     *
     * @mbg.generated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_name
     *
     * @param patientName the value for t_medical_record.patient_name
     *
     * @mbg.generated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_age
     *
     * @return the value of t_medical_record.patient_age
     *
     * @mbg.generated
     */
    public String getPatientAge() {
        return patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_age
     *
     * @param patientAge the value for t_medical_record.patient_age
     *
     * @mbg.generated
     */
    public void setPatientAge(String patientAge) {
        this.patientAge = patientAge == null ? null : patientAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_sex
     *
     * @return the value of t_medical_record.patient_sex
     *
     * @mbg.generated
     */
    public Integer getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_sex
     *
     * @param patientSex the value for t_medical_record.patient_sex
     *
     * @mbg.generated
     */
    public void setPatientSex(Integer patientSex) {
        this.patientSex = patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_id
     *
     * @return the value of t_medical_record.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_id
     *
     * @param doctorId the value for t_medical_record.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_name
     *
     * @return the value of t_medical_record.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_name
     *
     * @param doctorName the value for t_medical_record.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_teleno
     *
     * @return the value of t_medical_record.doctor_teleno
     *
     * @mbg.generated
     */
    public String getDoctorTeleno() {
        return doctorTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_teleno
     *
     * @param doctorTeleno the value for t_medical_record.doctor_teleno
     *
     * @mbg.generated
     */
    public void setDoctorTeleno(String doctorTeleno) {
        this.doctorTeleno = doctorTeleno == null ? null : doctorTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_avatar
     *
     * @return the value of t_medical_record.doctor_avatar
     *
     * @mbg.generated
     */
    public String getDoctorAvatar() {
        return doctorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_avatar
     *
     * @param doctorAvatar the value for t_medical_record.doctor_avatar
     *
     * @mbg.generated
     */
    public void setDoctorAvatar(String doctorAvatar) {
        this.doctorAvatar = doctorAvatar == null ? null : doctorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.hospital_id
     *
     * @return the value of t_medical_record.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.hospital_id
     *
     * @param hospitalId the value for t_medical_record.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.hospital_name
     *
     * @return the value of t_medical_record.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.hospital_name
     *
     * @param hospitalName the value for t_medical_record.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.department_id
     *
     * @return the value of t_medical_record.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.department_id
     *
     * @param departmentId the value for t_medical_record.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.department_name
     *
     * @return the value of t_medical_record.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.department_name
     *
     * @param departmentName the value for t_medical_record.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_cover
     *
     * @return the value of t_medical_record.medical_cover
     *
     * @mbg.generated
     */
    public String getMedicalCover() {
        return medicalCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_cover
     *
     * @param medicalCover the value for t_medical_record.medical_cover
     *
     * @mbg.generated
     */
    public void setMedicalCover(String medicalCover) {
        this.medicalCover = medicalCover == null ? null : medicalCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_no
     *
     * @return the value of t_medical_record.patient_no
     *
     * @mbg.generated
     */
    public String getPatientNo() {
        return patientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_no
     *
     * @param patientNo the value for t_medical_record.patient_no
     *
     * @mbg.generated
     */
    public void setPatientNo(String patientNo) {
        this.patientNo = patientNo == null ? null : patientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.admission_no
     *
     * @return the value of t_medical_record.admission_no
     *
     * @mbg.generated
     */
    public String getAdmissionNo() {
        return admissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.admission_no
     *
     * @param admissionNo the value for t_medical_record.admission_no
     *
     * @mbg.generated
     */
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo == null ? null : admissionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.bed_no
     *
     * @return the value of t_medical_record.bed_no
     *
     * @mbg.generated
     */
    public String getBedNo() {
        return bedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.bed_no
     *
     * @param bedNo the value for t_medical_record.bed_no
     *
     * @mbg.generated
     */
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo == null ? null : bedNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.record_no
     *
     * @return the value of t_medical_record.record_no
     *
     * @mbg.generated
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.record_no
     *
     * @param recordNo the value for t_medical_record.record_no
     *
     * @mbg.generated
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo == null ? null : recordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_date
     *
     * @return the value of t_medical_record.medical_date
     *
     * @mbg.generated
     */
    public Date getMedicalDate() {
        return medicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_date
     *
     * @param medicalDate the value for t_medical_record.medical_date
     *
     * @mbg.generated
     */
    public void setMedicalDate(Date medicalDate) {
        this.medicalDate = medicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_conclusion
     *
     * @return the value of t_medical_record.medical_conclusion
     *
     * @mbg.generated
     */
    public String getMedicalConclusion() {
        return medicalConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_conclusion
     *
     * @param medicalConclusion the value for t_medical_record.medical_conclusion
     *
     * @mbg.generated
     */
    public void setMedicalConclusion(String medicalConclusion) {
        this.medicalConclusion = medicalConclusion == null ? null : medicalConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_pictures
     *
     * @return the value of t_medical_record.medical_pictures
     *
     * @mbg.generated
     */
    public String getMedicalPictures() {
        return medicalPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_pictures
     *
     * @param medicalPictures the value for t_medical_record.medical_pictures
     *
     * @mbg.generated
     */
    public void setMedicalPictures(String medicalPictures) {
        this.medicalPictures = medicalPictures == null ? null : medicalPictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_video
     *
     * @return the value of t_medical_record.medical_video
     *
     * @mbg.generated
     */
    public String getMedicalVideo() {
        return medicalVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_video
     *
     * @param medicalVideo the value for t_medical_record.medical_video
     *
     * @mbg.generated
     */
    public void setMedicalVideo(String medicalVideo) {
        this.medicalVideo = medicalVideo == null ? null : medicalVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_code
     *
     * @return the value of t_medical_record.medical_code
     *
     * @mbg.generated
     */
    public String getMedicalCode() {
        return medicalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_code
     *
     * @param medicalCode the value for t_medical_record.medical_code
     *
     * @mbg.generated
     */
    public void setMedicalCode(String medicalCode) {
        this.medicalCode = medicalCode == null ? null : medicalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_left_vision
     *
     * @return the value of t_medical_record.eye_left_vision
     *
     * @mbg.generated
     */
    public String getEyeLeftVision() {
        return eyeLeftVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_left_vision
     *
     * @param eyeLeftVision the value for t_medical_record.eye_left_vision
     *
     * @mbg.generated
     */
    public void setEyeLeftVision(String eyeLeftVision) {
        this.eyeLeftVision = eyeLeftVision == null ? null : eyeLeftVision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_right_vision
     *
     * @return the value of t_medical_record.eye_right_vision
     *
     * @mbg.generated
     */
    public String getEyeRightVision() {
        return eyeRightVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_right_vision
     *
     * @param eyeRightVision the value for t_medical_record.eye_right_vision
     *
     * @mbg.generated
     */
    public void setEyeRightVision(String eyeRightVision) {
        this.eyeRightVision = eyeRightVision == null ? null : eyeRightVision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_left_img
     *
     * @return the value of t_medical_record.eye_left_img
     *
     * @mbg.generated
     */
    public String getEyeLeftImg() {
        return eyeLeftImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_left_img
     *
     * @param eyeLeftImg the value for t_medical_record.eye_left_img
     *
     * @mbg.generated
     */
    public void setEyeLeftImg(String eyeLeftImg) {
        this.eyeLeftImg = eyeLeftImg == null ? null : eyeLeftImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_right_img
     *
     * @return the value of t_medical_record.eye_right_img
     *
     * @mbg.generated
     */
    public String getEyeRightImg() {
        return eyeRightImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_right_img
     *
     * @param eyeRightImg the value for t_medical_record.eye_right_img
     *
     * @mbg.generated
     */
    public void setEyeRightImg(String eyeRightImg) {
        this.eyeRightImg = eyeRightImg == null ? null : eyeRightImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_left_video
     *
     * @return the value of t_medical_record.eye_left_video
     *
     * @mbg.generated
     */
    public String getEyeLeftVideo() {
        return eyeLeftVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_left_video
     *
     * @param eyeLeftVideo the value for t_medical_record.eye_left_video
     *
     * @mbg.generated
     */
    public void setEyeLeftVideo(String eyeLeftVideo) {
        this.eyeLeftVideo = eyeLeftVideo == null ? null : eyeLeftVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.eye_right_video
     *
     * @return the value of t_medical_record.eye_right_video
     *
     * @mbg.generated
     */
    public String getEyeRightVideo() {
        return eyeRightVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.eye_right_video
     *
     * @param eyeRightVideo the value for t_medical_record.eye_right_video
     *
     * @mbg.generated
     */
    public void setEyeRightVideo(String eyeRightVideo) {
        this.eyeRightVideo = eyeRightVideo == null ? null : eyeRightVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.report_status
     *
     * @return the value of t_medical_record.report_status
     *
     * @mbg.generated
     */
    public Integer getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.report_status
     *
     * @param reportStatus the value for t_medical_record.report_status
     *
     * @mbg.generated
     */
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.client_type
     *
     * @return the value of t_medical_record.client_type
     *
     * @mbg.generated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.client_type
     *
     * @param clientType the value for t_medical_record.client_type
     *
     * @mbg.generated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.create_by
     *
     * @return the value of t_medical_record.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.create_by
     *
     * @param createBy the value for t_medical_record.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.remarks
     *
     * @return the value of t_medical_record.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.remarks
     *
     * @param remarks the value for t_medical_record.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_enterprise
     *
     * @return the value of t_medical_record.is_enterprise
     *
     * @mbg.generated
     */
    public Integer getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_enterprise
     *
     * @param isEnterprise the value for t_medical_record.is_enterprise
     *
     * @mbg.generated
     */
    public void setIsEnterprise(Integer isEnterprise) {
        this.isEnterprise = isEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_remote
     *
     * @return the value of t_medical_record.is_remote
     *
     * @mbg.generated
     */
    public Integer getIsRemote() {
        return isRemote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_remote
     *
     * @param isRemote the value for t_medical_record.is_remote
     *
     * @mbg.generated
     */
    public void setIsRemote(Integer isRemote) {
        this.isRemote = isRemote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_base
     *
     * @return the value of t_medical_record.is_base
     *
     * @mbg.generated
     */
    public Integer getIsBase() {
        return isBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_base
     *
     * @param isBase the value for t_medical_record.is_base
     *
     * @mbg.generated
     */
    public void setIsBase(Integer isBase) {
        this.isBase = isBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_deleted
     *
     * @return the value of t_medical_record.is_deleted
     *
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_deleted
     *
     * @param isDeleted the value for t_medical_record.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}
