package com.terrydr.domain.eye;

import java.util.Date;

public class Encounter {

    private Integer departmentId;
    private String departmentName;

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.encrypt_id
     *
     * @mbg.generated
     */
    private String encryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.customer_encrypt_id
     *
     * @mbg.generated
     */
    private String customerEncryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.eye_type
     *
     * @mbg.generated
     */
    private Integer eyeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.symptom
     *
     * @mbg.generated
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.duration
     *
     * @mbg.generated
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.doctor_teleno
     *
     * @mbg.generated
     */
    private String doctorTeleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.doctor_avatar
     *
     * @mbg.generated
     */
    private String doctorAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.visit_date
     *
     * @mbg.generated
     */
    private Date visitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encounter.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.id
     *
     * @return the value of t_encounter.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.id
     *
     * @param id the value for t_encounter.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.encrypt_id
     *
     * @return the value of t_encounter.encrypt_id
     *
     * @mbg.generated
     */
    public String getEncryptId() {
        return encryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.encrypt_id
     *
     * @param encryptId the value for t_encounter.encrypt_id
     *
     * @mbg.generated
     */
    public void setEncryptId(String encryptId) {
        this.encryptId = encryptId == null ? null : encryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.customer_id
     *
     * @return the value of t_encounter.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.customer_id
     *
     * @param customerId the value for t_encounter.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.customer_encrypt_id
     *
     * @return the value of t_encounter.customer_encrypt_id
     *
     * @mbg.generated
     */
    public String getCustomerEncryptId() {
        return customerEncryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.customer_encrypt_id
     *
     * @param customerEncryptId the value for t_encounter.customer_encrypt_id
     *
     * @mbg.generated
     */
    public void setCustomerEncryptId(String customerEncryptId) {
        this.customerEncryptId = customerEncryptId == null ? null : customerEncryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.eye_type
     *
     * @return the value of t_encounter.eye_type
     *
     * @mbg.generated
     */
    public Integer getEyeType() {
        return eyeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.eye_type
     *
     * @param eyeType the value for t_encounter.eye_type
     *
     * @mbg.generated
     */
    public void setEyeType(Integer eyeType) {
        this.eyeType = eyeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.symptom
     *
     * @return the value of t_encounter.symptom
     *
     * @mbg.generated
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.symptom
     *
     * @param symptom the value for t_encounter.symptom
     *
     * @mbg.generated
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.duration
     *
     * @return the value of t_encounter.duration
     *
     * @mbg.generated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.duration
     *
     * @param duration the value for t_encounter.duration
     *
     * @mbg.generated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.doctor_id
     *
     * @return the value of t_encounter.doctor_id
     *
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.doctor_id
     *
     * @param doctorId the value for t_encounter.doctor_id
     *
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.doctor_name
     *
     * @return the value of t_encounter.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.doctor_name
     *
     * @param doctorName the value for t_encounter.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.doctor_teleno
     *
     * @return the value of t_encounter.doctor_teleno
     *
     * @mbg.generated
     */
    public String getDoctorTeleno() {
        return doctorTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.doctor_teleno
     *
     * @param doctorTeleno the value for t_encounter.doctor_teleno
     *
     * @mbg.generated
     */
    public void setDoctorTeleno(String doctorTeleno) {
        this.doctorTeleno = doctorTeleno == null ? null : doctorTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.doctor_avatar
     *
     * @return the value of t_encounter.doctor_avatar
     *
     * @mbg.generated
     */
    public String getDoctorAvatar() {
        return doctorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.doctor_avatar
     *
     * @param doctorAvatar the value for t_encounter.doctor_avatar
     *
     * @mbg.generated
     */
    public void setDoctorAvatar(String doctorAvatar) {
        this.doctorAvatar = doctorAvatar == null ? null : doctorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.hospital_id
     *
     * @return the value of t_encounter.hospital_id
     *
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.hospital_id
     *
     * @param hospitalId the value for t_encounter.hospital_id
     *
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.hospital_name
     *
     * @return the value of t_encounter.hospital_name
     *
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.hospital_name
     *
     * @param hospitalName the value for t_encounter.hospital_name
     *
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.cover
     *
     * @return the value of t_encounter.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.cover
     *
     * @param cover the value for t_encounter.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.visit_date
     *
     * @return the value of t_encounter.visit_date
     *
     * @mbg.generated
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.visit_date
     *
     * @param visitDate the value for t_encounter.visit_date
     *
     * @mbg.generated
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.create_time
     *
     * @return the value of t_encounter.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.create_time
     *
     * @param createTime the value for t_encounter.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.last_update_time
     *
     * @return the value of t_encounter.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.last_update_time
     *
     * @param lastUpdateTime the value for t_encounter.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encounter.is_delete
     *
     * @return the value of t_encounter.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encounter.is_delete
     *
     * @param isDelete the value for t_encounter.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}