package com.terrydr.domain.eye;

import java.util.Date;

public class Fundus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.encrypt_id
     *
     * @mbg.generated
     */
    private String encryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.encounter_id
     *
     * @mbg.generated
     */
    private Integer encounterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.encounter_encrypt_id
     *
     * @mbg.generated
     */
    private String encounterEncryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.left_img
     *
     * @mbg.generated
     */
    private String leftImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.right_img
     *
     * @mbg.generated
     */
    private String rightImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.left_video
     *
     * @mbg.generated
     */
    private String leftVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.right_video
     *
     * @mbg.generated
     */
    private String rightVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.collect_file
     *
     * @mbg.generated
     */
    private String collectFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_mydriasis
     *
     * @mbg.generated
     */
    private Integer lMydriasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_mydriasis
     *
     * @mbg.generated
     */
    private Integer rMydriasis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_retina
     *
     * @mbg.generated
     */
    private String lRetina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_retina
     *
     * @mbg.generated
     */
    private String rRetina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_cd
     *
     * @mbg.generated
     */
    private String lCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_cd
     *
     * @mbg.generated
     */
    private String rCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_optic_disc
     *
     * @mbg.generated
     */
    private String lOpticDisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_optic_disc
     *
     * @mbg.generated
     */
    private String rOpticDisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    private Integer lVitreousHemorrhage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    private Integer rVitreousHemorrhage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_diopter_opacification
     *
     * @mbg.generated
     */
    private Integer lDiopterOpacification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_diopter_opacification
     *
     * @mbg.generated
     */
    private Integer rDiopterOpacification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_av
     *
     * @mbg.generated
     */
    private String lAv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_av
     *
     * @mbg.generated
     */
    private String rAv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_retina_vasa
     *
     * @mbg.generated
     */
    private String lRetinaVasa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_retina_vasa
     *
     * @mbg.generated
     */
    private String rRetinaVasa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_macular_area
     *
     * @mbg.generated
     */
    private String lMacularArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_macular_area
     *
     * @mbg.generated
     */
    private String rMacularArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.l_peripheral_retina
     *
     * @mbg.generated
     */
    private String lPeripheralRetina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.r_peripheral_retina
     *
     * @mbg.generated
     */
    private String rPeripheralRetina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.report_status
     *
     * @mbg.generated
     */
    private Integer reportStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fundus.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.id
     *
     * @return the value of t_fundus.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.id
     *
     * @param id the value for t_fundus.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.encrypt_id
     *
     * @return the value of t_fundus.encrypt_id
     *
     * @mbg.generated
     */
    public String getEncryptId() {
        return encryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.encrypt_id
     *
     * @param encryptId the value for t_fundus.encrypt_id
     *
     * @mbg.generated
     */
    public void setEncryptId(String encryptId) {
        this.encryptId = encryptId == null ? null : encryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.encounter_id
     *
     * @return the value of t_fundus.encounter_id
     *
     * @mbg.generated
     */
    public Integer getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.encounter_id
     *
     * @param encounterId the value for t_fundus.encounter_id
     *
     * @mbg.generated
     */
    public void setEncounterId(Integer encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.encounter_encrypt_id
     *
     * @return the value of t_fundus.encounter_encrypt_id
     *
     * @mbg.generated
     */
    public String getEncounterEncryptId() {
        return encounterEncryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.encounter_encrypt_id
     *
     * @param encounterEncryptId the value for t_fundus.encounter_encrypt_id
     *
     * @mbg.generated
     */
    public void setEncounterEncryptId(String encounterEncryptId) {
        this.encounterEncryptId = encounterEncryptId == null ? null : encounterEncryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.left_img
     *
     * @return the value of t_fundus.left_img
     *
     * @mbg.generated
     */
    public String getLeftImg() {
        return leftImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.left_img
     *
     * @param leftImg the value for t_fundus.left_img
     *
     * @mbg.generated
     */
    public void setLeftImg(String leftImg) {
        this.leftImg = leftImg == null ? null : leftImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.right_img
     *
     * @return the value of t_fundus.right_img
     *
     * @mbg.generated
     */
    public String getRightImg() {
        return rightImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.right_img
     *
     * @param rightImg the value for t_fundus.right_img
     *
     * @mbg.generated
     */
    public void setRightImg(String rightImg) {
        this.rightImg = rightImg == null ? null : rightImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.left_video
     *
     * @return the value of t_fundus.left_video
     *
     * @mbg.generated
     */
    public String getLeftVideo() {
        return leftVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.left_video
     *
     * @param leftVideo the value for t_fundus.left_video
     *
     * @mbg.generated
     */
    public void setLeftVideo(String leftVideo) {
        this.leftVideo = leftVideo == null ? null : leftVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.right_video
     *
     * @return the value of t_fundus.right_video
     *
     * @mbg.generated
     */
    public String getRightVideo() {
        return rightVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.right_video
     *
     * @param rightVideo the value for t_fundus.right_video
     *
     * @mbg.generated
     */
    public void setRightVideo(String rightVideo) {
        this.rightVideo = rightVideo == null ? null : rightVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.collect_file
     *
     * @return the value of t_fundus.collect_file
     *
     * @mbg.generated
     */
    public String getCollectFile() {
        return collectFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.collect_file
     *
     * @param collectFile the value for t_fundus.collect_file
     *
     * @mbg.generated
     */
    public void setCollectFile(String collectFile) {
        this.collectFile = collectFile == null ? null : collectFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_mydriasis
     *
     * @return the value of t_fundus.l_mydriasis
     *
     * @mbg.generated
     */
    public Integer getlMydriasis() {
        return lMydriasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_mydriasis
     *
     * @param lMydriasis the value for t_fundus.l_mydriasis
     *
     * @mbg.generated
     */
    public void setlMydriasis(Integer lMydriasis) {
        this.lMydriasis = lMydriasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_mydriasis
     *
     * @return the value of t_fundus.r_mydriasis
     *
     * @mbg.generated
     */
    public Integer getrMydriasis() {
        return rMydriasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_mydriasis
     *
     * @param rMydriasis the value for t_fundus.r_mydriasis
     *
     * @mbg.generated
     */
    public void setrMydriasis(Integer rMydriasis) {
        this.rMydriasis = rMydriasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_retina
     *
     * @return the value of t_fundus.l_retina
     *
     * @mbg.generated
     */
    public String getlRetina() {
        return lRetina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_retina
     *
     * @param lRetina the value for t_fundus.l_retina
     *
     * @mbg.generated
     */
    public void setlRetina(String lRetina) {
        this.lRetina = lRetina == null ? null : lRetina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_retina
     *
     * @return the value of t_fundus.r_retina
     *
     * @mbg.generated
     */
    public String getrRetina() {
        return rRetina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_retina
     *
     * @param rRetina the value for t_fundus.r_retina
     *
     * @mbg.generated
     */
    public void setrRetina(String rRetina) {
        this.rRetina = rRetina == null ? null : rRetina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_cd
     *
     * @return the value of t_fundus.l_cd
     *
     * @mbg.generated
     */
    public String getlCd() {
        return lCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_cd
     *
     * @param lCd the value for t_fundus.l_cd
     *
     * @mbg.generated
     */
    public void setlCd(String lCd) {
        this.lCd = lCd == null ? null : lCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_cd
     *
     * @return the value of t_fundus.r_cd
     *
     * @mbg.generated
     */
    public String getrCd() {
        return rCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_cd
     *
     * @param rCd the value for t_fundus.r_cd
     *
     * @mbg.generated
     */
    public void setrCd(String rCd) {
        this.rCd = rCd == null ? null : rCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_optic_disc
     *
     * @return the value of t_fundus.l_optic_disc
     *
     * @mbg.generated
     */
    public String getlOpticDisc() {
        return lOpticDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_optic_disc
     *
     * @param lOpticDisc the value for t_fundus.l_optic_disc
     *
     * @mbg.generated
     */
    public void setlOpticDisc(String lOpticDisc) {
        this.lOpticDisc = lOpticDisc == null ? null : lOpticDisc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_optic_disc
     *
     * @return the value of t_fundus.r_optic_disc
     *
     * @mbg.generated
     */
    public String getrOpticDisc() {
        return rOpticDisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_optic_disc
     *
     * @param rOpticDisc the value for t_fundus.r_optic_disc
     *
     * @mbg.generated
     */
    public void setrOpticDisc(String rOpticDisc) {
        this.rOpticDisc = rOpticDisc == null ? null : rOpticDisc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_vitreous_hemorrhage
     *
     * @return the value of t_fundus.l_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    public Integer getlVitreousHemorrhage() {
        return lVitreousHemorrhage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_vitreous_hemorrhage
     *
     * @param lVitreousHemorrhage the value for t_fundus.l_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    public void setlVitreousHemorrhage(Integer lVitreousHemorrhage) {
        this.lVitreousHemorrhage = lVitreousHemorrhage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_vitreous_hemorrhage
     *
     * @return the value of t_fundus.r_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    public Integer getrVitreousHemorrhage() {
        return rVitreousHemorrhage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_vitreous_hemorrhage
     *
     * @param rVitreousHemorrhage the value for t_fundus.r_vitreous_hemorrhage
     *
     * @mbg.generated
     */
    public void setrVitreousHemorrhage(Integer rVitreousHemorrhage) {
        this.rVitreousHemorrhage = rVitreousHemorrhage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_diopter_opacification
     *
     * @return the value of t_fundus.l_diopter_opacification
     *
     * @mbg.generated
     */
    public Integer getlDiopterOpacification() {
        return lDiopterOpacification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_diopter_opacification
     *
     * @param lDiopterOpacification the value for t_fundus.l_diopter_opacification
     *
     * @mbg.generated
     */
    public void setlDiopterOpacification(Integer lDiopterOpacification) {
        this.lDiopterOpacification = lDiopterOpacification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_diopter_opacification
     *
     * @return the value of t_fundus.r_diopter_opacification
     *
     * @mbg.generated
     */
    public Integer getrDiopterOpacification() {
        return rDiopterOpacification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_diopter_opacification
     *
     * @param rDiopterOpacification the value for t_fundus.r_diopter_opacification
     *
     * @mbg.generated
     */
    public void setrDiopterOpacification(Integer rDiopterOpacification) {
        this.rDiopterOpacification = rDiopterOpacification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_av
     *
     * @return the value of t_fundus.l_av
     *
     * @mbg.generated
     */
    public String getlAv() {
        return lAv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_av
     *
     * @param lAv the value for t_fundus.l_av
     *
     * @mbg.generated
     */
    public void setlAv(String lAv) {
        this.lAv = lAv == null ? null : lAv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_av
     *
     * @return the value of t_fundus.r_av
     *
     * @mbg.generated
     */
    public String getrAv() {
        return rAv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_av
     *
     * @param rAv the value for t_fundus.r_av
     *
     * @mbg.generated
     */
    public void setrAv(String rAv) {
        this.rAv = rAv == null ? null : rAv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_retina_vasa
     *
     * @return the value of t_fundus.l_retina_vasa
     *
     * @mbg.generated
     */
    public String getlRetinaVasa() {
        return lRetinaVasa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_retina_vasa
     *
     * @param lRetinaVasa the value for t_fundus.l_retina_vasa
     *
     * @mbg.generated
     */
    public void setlRetinaVasa(String lRetinaVasa) {
        this.lRetinaVasa = lRetinaVasa == null ? null : lRetinaVasa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_retina_vasa
     *
     * @return the value of t_fundus.r_retina_vasa
     *
     * @mbg.generated
     */
    public String getrRetinaVasa() {
        return rRetinaVasa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_retina_vasa
     *
     * @param rRetinaVasa the value for t_fundus.r_retina_vasa
     *
     * @mbg.generated
     */
    public void setrRetinaVasa(String rRetinaVasa) {
        this.rRetinaVasa = rRetinaVasa == null ? null : rRetinaVasa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_macular_area
     *
     * @return the value of t_fundus.l_macular_area
     *
     * @mbg.generated
     */
    public String getlMacularArea() {
        return lMacularArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_macular_area
     *
     * @param lMacularArea the value for t_fundus.l_macular_area
     *
     * @mbg.generated
     */
    public void setlMacularArea(String lMacularArea) {
        this.lMacularArea = lMacularArea == null ? null : lMacularArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_macular_area
     *
     * @return the value of t_fundus.r_macular_area
     *
     * @mbg.generated
     */
    public String getrMacularArea() {
        return rMacularArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_macular_area
     *
     * @param rMacularArea the value for t_fundus.r_macular_area
     *
     * @mbg.generated
     */
    public void setrMacularArea(String rMacularArea) {
        this.rMacularArea = rMacularArea == null ? null : rMacularArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.l_peripheral_retina
     *
     * @return the value of t_fundus.l_peripheral_retina
     *
     * @mbg.generated
     */
    public String getlPeripheralRetina() {
        return lPeripheralRetina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.l_peripheral_retina
     *
     * @param lPeripheralRetina the value for t_fundus.l_peripheral_retina
     *
     * @mbg.generated
     */
    public void setlPeripheralRetina(String lPeripheralRetina) {
        this.lPeripheralRetina = lPeripheralRetina == null ? null : lPeripheralRetina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.r_peripheral_retina
     *
     * @return the value of t_fundus.r_peripheral_retina
     *
     * @mbg.generated
     */
    public String getrPeripheralRetina() {
        return rPeripheralRetina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.r_peripheral_retina
     *
     * @param rPeripheralRetina the value for t_fundus.r_peripheral_retina
     *
     * @mbg.generated
     */
    public void setrPeripheralRetina(String rPeripheralRetina) {
        this.rPeripheralRetina = rPeripheralRetina == null ? null : rPeripheralRetina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.cover
     *
     * @return the value of t_fundus.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.cover
     *
     * @param cover the value for t_fundus.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.remark
     *
     * @return the value of t_fundus.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.remark
     *
     * @param remark the value for t_fundus.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.report_status
     *
     * @return the value of t_fundus.report_status
     *
     * @mbg.generated
     */
    public Integer getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.report_status
     *
     * @param reportStatus the value for t_fundus.report_status
     *
     * @mbg.generated
     */
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.note
     *
     * @return the value of t_fundus.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.note
     *
     * @param note the value for t_fundus.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.create_time
     *
     * @return the value of t_fundus.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.create_time
     *
     * @param createTime the value for t_fundus.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.last_update_time
     *
     * @return the value of t_fundus.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.last_update_time
     *
     * @param lastUpdateTime the value for t_fundus.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fundus.is_delete
     *
     * @return the value of t_fundus.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fundus.is_delete
     *
     * @param isDelete the value for t_fundus.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}