package com.terrydr.domain.eye;

import java.util.Date;

public class GeneralExamination {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.encrypt_id
     *
     * @mbg.generated
     */
    private String encryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.encounter_id
     *
     * @mbg.generated
     */
    private Integer encounterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.encounter_encrypt_id
     *
     * @mbg.generated
     */
    private String encounterEncryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.collect_file
     *
     * @mbg.generated
     */
    private String collectFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_nv
     *
     * @mbg.generated
     */
    private String lNv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_nv
     *
     * @mbg.generated
     */
    private String rNv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_is_glasses
     *
     * @mbg.generated
     */
    private Integer lIsGlasses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_is_glasses
     *
     * @mbg.generated
     */
    private Integer rIsGlasses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_glasses_vision
     *
     * @mbg.generated
     */
    private String lGlassesVision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_glasses_vision
     *
     * @mbg.generated
     */
    private String rGlassesVision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_cva
     *
     * @mbg.generated
     */
    private String lCva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_cva
     *
     * @mbg.generated
     */
    private String rCva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_intraocular_pressure
     *
     * @mbg.generated
     */
    private String lIntraocularPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_intraocular_pressure
     *
     * @mbg.generated
     */
    private String rIntraocularPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_eye_position
     *
     * @mbg.generated
     */
    private String lEyePosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_eye_position
     *
     * @mbg.generated
     */
    private String rEyePosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_eye_movement
     *
     * @mbg.generated
     */
    private String lEyeMovement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_eye_movement
     *
     * @mbg.generated
     */
    private String rEyeMovement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.l_eyelids
     *
     * @mbg.generated
     */
    private String lEyelids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.r_eyelids
     *
     * @mbg.generated
     */
    private String rEyelids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.last_update_time
     *
     * @mbg.generated
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_general_examination.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.id
     *
     * @return the value of t_general_examination.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.id
     *
     * @param id the value for t_general_examination.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.encrypt_id
     *
     * @return the value of t_general_examination.encrypt_id
     *
     * @mbg.generated
     */
    public String getEncryptId() {
        return encryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.encrypt_id
     *
     * @param encryptId the value for t_general_examination.encrypt_id
     *
     * @mbg.generated
     */
    public void setEncryptId(String encryptId) {
        this.encryptId = encryptId == null ? null : encryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.encounter_id
     *
     * @return the value of t_general_examination.encounter_id
     *
     * @mbg.generated
     */
    public Integer getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.encounter_id
     *
     * @param encounterId the value for t_general_examination.encounter_id
     *
     * @mbg.generated
     */
    public void setEncounterId(Integer encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.encounter_encrypt_id
     *
     * @return the value of t_general_examination.encounter_encrypt_id
     *
     * @mbg.generated
     */
    public String getEncounterEncryptId() {
        return encounterEncryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.encounter_encrypt_id
     *
     * @param encounterEncryptId the value for t_general_examination.encounter_encrypt_id
     *
     * @mbg.generated
     */
    public void setEncounterEncryptId(String encounterEncryptId) {
        this.encounterEncryptId = encounterEncryptId == null ? null : encounterEncryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.collect_file
     *
     * @return the value of t_general_examination.collect_file
     *
     * @mbg.generated
     */
    public String getCollectFile() {
        return collectFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.collect_file
     *
     * @param collectFile the value for t_general_examination.collect_file
     *
     * @mbg.generated
     */
    public void setCollectFile(String collectFile) {
        this.collectFile = collectFile == null ? null : collectFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_nv
     *
     * @return the value of t_general_examination.l_nv
     *
     * @mbg.generated
     */
    public String getlNv() {
        return lNv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_nv
     *
     * @param lNv the value for t_general_examination.l_nv
     *
     * @mbg.generated
     */
    public void setlNv(String lNv) {
        this.lNv = lNv == null ? null : lNv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_nv
     *
     * @return the value of t_general_examination.r_nv
     *
     * @mbg.generated
     */
    public String getrNv() {
        return rNv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_nv
     *
     * @param rNv the value for t_general_examination.r_nv
     *
     * @mbg.generated
     */
    public void setrNv(String rNv) {
        this.rNv = rNv == null ? null : rNv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_is_glasses
     *
     * @return the value of t_general_examination.l_is_glasses
     *
     * @mbg.generated
     */
    public Integer getlIsGlasses() {
        return lIsGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_is_glasses
     *
     * @param lIsGlasses the value for t_general_examination.l_is_glasses
     *
     * @mbg.generated
     */
    public void setlIsGlasses(Integer lIsGlasses) {
        this.lIsGlasses = lIsGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_is_glasses
     *
     * @return the value of t_general_examination.r_is_glasses
     *
     * @mbg.generated
     */
    public Integer getrIsGlasses() {
        return rIsGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_is_glasses
     *
     * @param rIsGlasses the value for t_general_examination.r_is_glasses
     *
     * @mbg.generated
     */
    public void setrIsGlasses(Integer rIsGlasses) {
        this.rIsGlasses = rIsGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_glasses_vision
     *
     * @return the value of t_general_examination.l_glasses_vision
     *
     * @mbg.generated
     */
    public String getlGlassesVision() {
        return lGlassesVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_glasses_vision
     *
     * @param lGlassesVision the value for t_general_examination.l_glasses_vision
     *
     * @mbg.generated
     */
    public void setlGlassesVision(String lGlassesVision) {
        this.lGlassesVision = lGlassesVision == null ? null : lGlassesVision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_glasses_vision
     *
     * @return the value of t_general_examination.r_glasses_vision
     *
     * @mbg.generated
     */
    public String getrGlassesVision() {
        return rGlassesVision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_glasses_vision
     *
     * @param rGlassesVision the value for t_general_examination.r_glasses_vision
     *
     * @mbg.generated
     */
    public void setrGlassesVision(String rGlassesVision) {
        this.rGlassesVision = rGlassesVision == null ? null : rGlassesVision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_cva
     *
     * @return the value of t_general_examination.l_cva
     *
     * @mbg.generated
     */
    public String getlCva() {
        return lCva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_cva
     *
     * @param lCva the value for t_general_examination.l_cva
     *
     * @mbg.generated
     */
    public void setlCva(String lCva) {
        this.lCva = lCva == null ? null : lCva.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_cva
     *
     * @return the value of t_general_examination.r_cva
     *
     * @mbg.generated
     */
    public String getrCva() {
        return rCva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_cva
     *
     * @param rCva the value for t_general_examination.r_cva
     *
     * @mbg.generated
     */
    public void setrCva(String rCva) {
        this.rCva = rCva == null ? null : rCva.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_intraocular_pressure
     *
     * @return the value of t_general_examination.l_intraocular_pressure
     *
     * @mbg.generated
     */
    public String getlIntraocularPressure() {
        return lIntraocularPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_intraocular_pressure
     *
     * @param lIntraocularPressure the value for t_general_examination.l_intraocular_pressure
     *
     * @mbg.generated
     */
    public void setlIntraocularPressure(String lIntraocularPressure) {
        this.lIntraocularPressure = lIntraocularPressure == null ? null : lIntraocularPressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_intraocular_pressure
     *
     * @return the value of t_general_examination.r_intraocular_pressure
     *
     * @mbg.generated
     */
    public String getrIntraocularPressure() {
        return rIntraocularPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_intraocular_pressure
     *
     * @param rIntraocularPressure the value for t_general_examination.r_intraocular_pressure
     *
     * @mbg.generated
     */
    public void setrIntraocularPressure(String rIntraocularPressure) {
        this.rIntraocularPressure = rIntraocularPressure == null ? null : rIntraocularPressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_eye_position
     *
     * @return the value of t_general_examination.l_eye_position
     *
     * @mbg.generated
     */
    public String getlEyePosition() {
        return lEyePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_eye_position
     *
     * @param lEyePosition the value for t_general_examination.l_eye_position
     *
     * @mbg.generated
     */
    public void setlEyePosition(String lEyePosition) {
        this.lEyePosition = lEyePosition == null ? null : lEyePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_eye_position
     *
     * @return the value of t_general_examination.r_eye_position
     *
     * @mbg.generated
     */
    public String getrEyePosition() {
        return rEyePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_eye_position
     *
     * @param rEyePosition the value for t_general_examination.r_eye_position
     *
     * @mbg.generated
     */
    public void setrEyePosition(String rEyePosition) {
        this.rEyePosition = rEyePosition == null ? null : rEyePosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_eye_movement
     *
     * @return the value of t_general_examination.l_eye_movement
     *
     * @mbg.generated
     */
    public String getlEyeMovement() {
        return lEyeMovement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_eye_movement
     *
     * @param lEyeMovement the value for t_general_examination.l_eye_movement
     *
     * @mbg.generated
     */
    public void setlEyeMovement(String lEyeMovement) {
        this.lEyeMovement = lEyeMovement == null ? null : lEyeMovement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_eye_movement
     *
     * @return the value of t_general_examination.r_eye_movement
     *
     * @mbg.generated
     */
    public String getrEyeMovement() {
        return rEyeMovement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_eye_movement
     *
     * @param rEyeMovement the value for t_general_examination.r_eye_movement
     *
     * @mbg.generated
     */
    public void setrEyeMovement(String rEyeMovement) {
        this.rEyeMovement = rEyeMovement == null ? null : rEyeMovement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.l_eyelids
     *
     * @return the value of t_general_examination.l_eyelids
     *
     * @mbg.generated
     */
    public String getlEyelids() {
        return lEyelids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.l_eyelids
     *
     * @param lEyelids the value for t_general_examination.l_eyelids
     *
     * @mbg.generated
     */
    public void setlEyelids(String lEyelids) {
        this.lEyelids = lEyelids == null ? null : lEyelids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.r_eyelids
     *
     * @return the value of t_general_examination.r_eyelids
     *
     * @mbg.generated
     */
    public String getrEyelids() {
        return rEyelids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.r_eyelids
     *
     * @param rEyelids the value for t_general_examination.r_eyelids
     *
     * @mbg.generated
     */
    public void setrEyelids(String rEyelids) {
        this.rEyelids = rEyelids == null ? null : rEyelids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.cover
     *
     * @return the value of t_general_examination.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.cover
     *
     * @param cover the value for t_general_examination.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.remark
     *
     * @return the value of t_general_examination.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.remark
     *
     * @param remark the value for t_general_examination.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.note
     *
     * @return the value of t_general_examination.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.note
     *
     * @param note the value for t_general_examination.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.create_time
     *
     * @return the value of t_general_examination.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.create_time
     *
     * @param createTime the value for t_general_examination.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.last_update_time
     *
     * @return the value of t_general_examination.last_update_time
     *
     * @mbg.generated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.last_update_time
     *
     * @param lastUpdateTime the value for t_general_examination.last_update_time
     *
     * @mbg.generated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_general_examination.is_delete
     *
     * @return the value of t_general_examination.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_general_examination.is_delete
     *
     * @param isDelete the value for t_general_examination.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}