package com.terrydr.domain.eye;

import java.util.Date;

public class ScreenInterval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.dm_type
     *
     * @mbg.generated
     */
    private Boolean dmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.dx_date
     *
     * @mbg.generated
     */
    private Date dxDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.ghb
     *
     * @mbg.generated
     */
    private String ghb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.sp
     *
     * @mbg.generated
     */
    private String sp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.screen_interval
     *
     * @mbg.generated
     */
    private String screenInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.screen_date
     *
     * @mbg.generated
     */
    private Date screenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.examine_id
     *
     * @mbg.generated
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.examine_encrypt_id
     *
     * @mbg.generated
     */
    private String examineEncryptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_interval.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.id
     *
     * @return the value of t_screen_interval.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.id
     *
     * @param id the value for t_screen_interval.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.dm_type
     *
     * @return the value of t_screen_interval.dm_type
     *
     * @mbg.generated
     */
    public Boolean getDmType() {
        return dmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.dm_type
     *
     * @param dmType the value for t_screen_interval.dm_type
     *
     * @mbg.generated
     */
    public void setDmType(Boolean dmType) {
        this.dmType = dmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.dx_date
     *
     * @return the value of t_screen_interval.dx_date
     *
     * @mbg.generated
     */
    public Date getDxDate() {
        return dxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.dx_date
     *
     * @param dxDate the value for t_screen_interval.dx_date
     *
     * @mbg.generated
     */
    public void setDxDate(Date dxDate) {
        this.dxDate = dxDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.ghb
     *
     * @return the value of t_screen_interval.ghb
     *
     * @mbg.generated
     */
    public String getGhb() {
        return ghb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.ghb
     *
     * @param ghb the value for t_screen_interval.ghb
     *
     * @mbg.generated
     */
    public void setGhb(String ghb) {
        this.ghb = ghb == null ? null : ghb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.sp
     *
     * @return the value of t_screen_interval.sp
     *
     * @mbg.generated
     */
    public String getSp() {
        return sp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.sp
     *
     * @param sp the value for t_screen_interval.sp
     *
     * @mbg.generated
     */
    public void setSp(String sp) {
        this.sp = sp == null ? null : sp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.screen_interval
     *
     * @return the value of t_screen_interval.screen_interval
     *
     * @mbg.generated
     */
    public String getScreenInterval() {
        return screenInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.screen_interval
     *
     * @param screenInterval the value for t_screen_interval.screen_interval
     *
     * @mbg.generated
     */
    public void setScreenInterval(String screenInterval) {
        this.screenInterval = screenInterval == null ? null : screenInterval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.screen_date
     *
     * @return the value of t_screen_interval.screen_date
     *
     * @mbg.generated
     */
    public Date getScreenDate() {
        return screenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.screen_date
     *
     * @param screenDate the value for t_screen_interval.screen_date
     *
     * @mbg.generated
     */
    public void setScreenDate(Date screenDate) {
        this.screenDate = screenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.examine_id
     *
     * @return the value of t_screen_interval.examine_id
     *
     * @mbg.generated
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.examine_id
     *
     * @param examineId the value for t_screen_interval.examine_id
     *
     * @mbg.generated
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.examine_encrypt_id
     *
     * @return the value of t_screen_interval.examine_encrypt_id
     *
     * @mbg.generated
     */
    public String getExamineEncryptId() {
        return examineEncryptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.examine_encrypt_id
     *
     * @param examineEncryptId the value for t_screen_interval.examine_encrypt_id
     *
     * @mbg.generated
     */
    public void setExamineEncryptId(String examineEncryptId) {
        this.examineEncryptId = examineEncryptId == null ? null : examineEncryptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_interval.create_time
     *
     * @return the value of t_screen_interval.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_interval.create_time
     *
     * @param createTime the value for t_screen_interval.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}