package com.terrydr.dao.eye;

import com.terrydr.domain.eye.AnteriorSegment;

public interface AnteriorSegmentDAO {

    int deleteAll();

    void drop();

    void createTable();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    int insert(AnteriorSegment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    int insertSelective(AnteriorSegment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    AnteriorSegment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnteriorSegment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_anterior_segment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnteriorSegment record);
}