package com.terrydr.dao.eye;

import com.terrydr.domain.eye.Consultation;

public interface ConsultationDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insert(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insertSelective(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    Consultation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Consultation record);
}