package com.terrydr.dao.eye;

import com.terrydr.domain.eye.Encounter;

public interface EncounterDAO {

    String getEncryptId(Integer id);

    int deleteAll();

    void drop();

    void createTable();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    int insert(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    int insertSelective(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    Encounter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encounter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Encounter record);
}