package com.terrydr.dao.eye;

import com.terrydr.domain.eye.EYEConsultation;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EYEConsultationDAO {
    int deleteAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insert(EYEConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insertSelective(EYEConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    EYEConsultation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EYEConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EYEConsultation record);
}