package com.terrydr.dao.eye;

import com.terrydr.domain.ReportDetail;
import com.terrydr.domain.eye.EyeReport;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EyeReportDAO {

    int updateReportCoverByReportId(@Param("reportId") Integer reportId, @Param("reportCover") String reportCover);

    int updateReportTypeByRecordId(@Param("type") int[] type);

    int deleteAll();

    /**
     * 分页查询
     * @return
     */
    List<EyeReport> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    /**
     * 全部查询
     * @return
     */
    List<EyeReport> selectAll();

    /**
     * 查询总数
     * @return
     */
    int count();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int insert(EyeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int insertSelective(EyeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    EyeReport selectByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EyeReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EyeReport record);
}