package com.terrydr.dao.eye;

import com.terrydr.domain.eye.EYEScreenInterval;
import org.springframework.stereotype.Repository;

@Repository
public interface EYEScreenIntervalDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insert(EYEScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insertSelective(EYEScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    EYEScreenInterval selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EYEScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EYEScreenInterval record);
}