package com.terrydr.dao.eye;

import com.terrydr.domain.eye.Fundus;

public interface FundusDAO {

    int deleteAll();

    void drop();

    void createTable();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    int insert(Fundus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    int insertSelective(Fundus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    Fundus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Fundus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fundus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fundus record);
}