package com.terrydr.dao.eye;

import com.terrydr.domain.eye.GeneralExamination;

public interface GeneralExaminationDAO {

    int deleteAll();

    int deleteOptometry();

    int deleteVisionExam();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    int insert(GeneralExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    int insertSelective(GeneralExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    GeneralExamination selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GeneralExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_general_examination
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GeneralExamination record);
}