package com.terrydr.dao.eye;

import com.terrydr.domain.eye.Report;

public interface ReportDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    Report selectByPrimaryKey(Integer reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Report record);
}