package com.terrydr.dao.eye;

import com.terrydr.domain.eye.ScreenInterval;

public interface ScreenIntervalDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insert(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insertSelective(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    ScreenInterval selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScreenInterval record);
}