package com.terrydr.domain.ecg;

import com.terrydr.domain.FatherBean;
import com.terrydr.domain.MedicalRecord;
import com.terrydr.domain.MedicalRecordDetail;

import java.util.Date;

public class ECGMedicalRecord extends FatherBean{

    public ECGMedicalRecord(ECGMedicalRecord_UpdateAttrValue value) {
        this.recordId = value.getRecordId();
        try {
            this.heartRate = value.getHeartRate() != null ? Integer.parseInt(value.getHeartRate()) : null;
        }catch (NumberFormatException e){
            this.heartRate = 0;
        }
        this.classification = value.getClassification() != null ? Integer.parseInt(value.getClassification()) : null;
    }

    public ECGMedicalRecord(MedicalRecord_UpdateRedundant redundant) {
        this.recordId = redundant.getRecordId();
        this.doctorTeleno = redundant.getDoctorTeleno();
        this.departmentName = redundant.getDepartmentName();
        this.hospitalName = redundant.getHospitalName();
    }

    public ECGMedicalRecord(MedicalRecordDetail medicalRecord) {
        this.recordId = medicalRecord.getRecordId();
        this.doctorTeleno = medicalRecord.getDoctorTeleno();
        this.hospitalName = medicalRecord.getHospitalName();
        this.departmentName = medicalRecord.getDepartmentName();
        this.patientId = medicalRecord.getPatientId();
        this.patientTeleno = medicalRecord.getPatientTeleno();
        this.patientName = medicalRecord.getPatientName();
        this.patientAge = medicalRecord.getPatientAge();
        this.patientSex = medicalRecord.getPatientSex() != null ? Integer.parseInt(medicalRecord.getPatientSex()) : null;
        this.hospitalId = medicalRecord.getHospitalId();
        this.doctorId = medicalRecord.getDoctorId();
        this.doctorName = medicalRecord.getDoctorName();
        this.doctorAvatar = medicalRecord.getDoctorAvatar();
        this.departmentId = medicalRecord.getDepartmentId();
        this.medicalCover = medicalRecord.getMedicalCover();
        this.admissionNo = medicalRecord.getAdmissionNo();
        this.bedNo = medicalRecord.getBedNo();
        this.recordNo = medicalRecord.getRecordNo();
        this.medicalDate = medicalRecord.getMedicalDate();
        this.medicalConclusion = medicalRecord.getMedicalConclusion();
        this.medicalPictures = medicalRecord.getMedicalPictures();
        this.createBy = medicalRecord.getCreateBy();
        this.isDeleted = medicalRecord.getIsDeleted();
        this.medicalCode = medicalRecord.getMedicalCode();
        this.reportStatus = medicalRecord.getReportStatus();
        this.deviceCode = medicalRecord.getDeviceCode();
        this.shareId = medicalRecord.getShareId();
        this.isRemote = medicalRecord.getIsRemote() != null ? Integer.parseInt(medicalRecord.getIsRemote()) : null;
        this.remarks = medicalRecord.getRemarks();
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_id
     *
     * @mbg.generated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_teleno
     *
     * @mbg.generated
     */
    private String patientTeleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_name
     *
     * @mbg.generated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_age
     *
     * @mbg.generated
     */
    private String patientAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.patient_sex
     *
     * @mbg.generated
     */
    private Integer patientSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.hospital_id
     *
     * @mbg.generated
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_id
     *
     * @mbg.generated
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_teleno
     *
     * @mbg.generated
     */
    private String doctorTeleno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doctor_avatar
     *
     * @mbg.generated
     */
    private String doctorAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.hospital_name
     *
     * @mbg.generated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_cover
     *
     * @mbg.generated
     */
    private String medicalCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.admission_no
     *
     * @mbg.generated
     */
    private String admissionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.bed_no
     *
     * @mbg.generated
     */
    private String bedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.record_no
     *
     * @mbg.generated
     */
    private String recordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_date
     *
     * @mbg.generated
     */
    private Date medicalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_conclusion
     *
     * @mbg.generated
     */
    private String medicalConclusion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_pictures
     *
     * @mbg.generated
     */
    private String medicalPictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.heart_rate
     *
     * @mbg.generated
     */
    private Integer heartRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.classification
     *
     * @mbg.generated
     */
    private Integer classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_deleted
     *
     * @mbg.generated
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_code
     *
     * @mbg.generated
     */
    private String medicalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.report_status
     *
     * @mbg.generated
     */
    private Integer reportStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.share_id
     *
     * @mbg.generated
     */
    private String shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_remote
     *
     * @mbg.generated
     */
    private Integer isRemote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.record_id
     *
     * @return the value of t_medical_record.record_id
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.record_id
     *
     * @param recordId the value for t_medical_record.record_id
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_id
     *
     * @return the value of t_medical_record.patient_id
     * @mbg.generated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_id
     *
     * @param patientId the value for t_medical_record.patient_id
     * @mbg.generated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_teleno
     *
     * @return the value of t_medical_record.patient_teleno
     * @mbg.generated
     */
    public String getPatientTeleno() {
        return patientTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_teleno
     *
     * @param patientTeleno the value for t_medical_record.patient_teleno
     * @mbg.generated
     */
    public void setPatientTeleno(String patientTeleno) {
        this.patientTeleno = patientTeleno == null ? null : patientTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_name
     *
     * @return the value of t_medical_record.patient_name
     * @mbg.generated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_name
     *
     * @param patientName the value for t_medical_record.patient_name
     * @mbg.generated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_age
     *
     * @return the value of t_medical_record.patient_age
     * @mbg.generated
     */
    public String getPatientAge() {
        return patientAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_age
     *
     * @param patientAge the value for t_medical_record.patient_age
     * @mbg.generated
     */
    public void setPatientAge(String patientAge) {
        this.patientAge = patientAge == null ? null : patientAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.patient_sex
     *
     * @return the value of t_medical_record.patient_sex
     * @mbg.generated
     */
    public Integer getPatientSex() {
        return patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.patient_sex
     *
     * @param patientSex the value for t_medical_record.patient_sex
     * @mbg.generated
     */
    public void setPatientSex(Integer patientSex) {
        this.patientSex = patientSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.hospital_id
     *
     * @return the value of t_medical_record.hospital_id
     * @mbg.generated
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.hospital_id
     *
     * @param hospitalId the value for t_medical_record.hospital_id
     * @mbg.generated
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_id
     *
     * @return the value of t_medical_record.doctor_id
     * @mbg.generated
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_id
     *
     * @param doctorId the value for t_medical_record.doctor_id
     * @mbg.generated
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_name
     *
     * @return the value of t_medical_record.doctor_name
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_name
     *
     * @param doctorName the value for t_medical_record.doctor_name
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_teleno
     *
     * @return the value of t_medical_record.doctor_teleno
     * @mbg.generated
     */
    public String getDoctorTeleno() {
        return doctorTeleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_teleno
     *
     * @param doctorTeleno the value for t_medical_record.doctor_teleno
     * @mbg.generated
     */
    public void setDoctorTeleno(String doctorTeleno) {
        this.doctorTeleno = doctorTeleno == null ? null : doctorTeleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doctor_avatar
     *
     * @return the value of t_medical_record.doctor_avatar
     * @mbg.generated
     */
    public String getDoctorAvatar() {
        return doctorAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doctor_avatar
     *
     * @param doctorAvatar the value for t_medical_record.doctor_avatar
     * @mbg.generated
     */
    public void setDoctorAvatar(String doctorAvatar) {
        this.doctorAvatar = doctorAvatar == null ? null : doctorAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.hospital_name
     *
     * @return the value of t_medical_record.hospital_name
     * @mbg.generated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.hospital_name
     *
     * @param hospitalName the value for t_medical_record.hospital_name
     * @mbg.generated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.department_id
     *
     * @return the value of t_medical_record.department_id
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.department_id
     *
     * @param departmentId the value for t_medical_record.department_id
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.department_name
     *
     * @return the value of t_medical_record.department_name
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.department_name
     *
     * @param departmentName the value for t_medical_record.department_name
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_cover
     *
     * @return the value of t_medical_record.medical_cover
     * @mbg.generated
     */
    public String getMedicalCover() {
        return medicalCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_cover
     *
     * @param medicalCover the value for t_medical_record.medical_cover
     * @mbg.generated
     */
    public void setMedicalCover(String medicalCover) {
        this.medicalCover = medicalCover == null ? null : medicalCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.admission_no
     *
     * @return the value of t_medical_record.admission_no
     * @mbg.generated
     */
    public String getAdmissionNo() {
        return admissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.admission_no
     *
     * @param admissionNo the value for t_medical_record.admission_no
     * @mbg.generated
     */
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo == null ? null : admissionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.bed_no
     *
     * @return the value of t_medical_record.bed_no
     * @mbg.generated
     */
    public String getBedNo() {
        return bedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.bed_no
     *
     * @param bedNo the value for t_medical_record.bed_no
     * @mbg.generated
     */
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo == null ? null : bedNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.record_no
     *
     * @return the value of t_medical_record.record_no
     * @mbg.generated
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.record_no
     *
     * @param recordNo the value for t_medical_record.record_no
     * @mbg.generated
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo == null ? null : recordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_date
     *
     * @return the value of t_medical_record.medical_date
     * @mbg.generated
     */
    public Date getMedicalDate() {
        return medicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_date
     *
     * @param medicalDate the value for t_medical_record.medical_date
     * @mbg.generated
     */
    public void setMedicalDate(Date medicalDate) {
        this.medicalDate = medicalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_conclusion
     *
     * @return the value of t_medical_record.medical_conclusion
     * @mbg.generated
     */
    public String getMedicalConclusion() {
        return medicalConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_conclusion
     *
     * @param medicalConclusion the value for t_medical_record.medical_conclusion
     * @mbg.generated
     */
    public void setMedicalConclusion(String medicalConclusion) {
        this.medicalConclusion = medicalConclusion == null ? null : medicalConclusion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_pictures
     *
     * @return the value of t_medical_record.medical_pictures
     * @mbg.generated
     */
    public String getMedicalPictures() {
        return medicalPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_pictures
     *
     * @param medicalPictures the value for t_medical_record.medical_pictures
     * @mbg.generated
     */
    public void setMedicalPictures(String medicalPictures) {
        this.medicalPictures = medicalPictures == null ? null : medicalPictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.heart_rate
     *
     * @return the value of t_medical_record.heart_rate
     * @mbg.generated
     */
    public Integer getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.heart_rate
     *
     * @param heartRate the value for t_medical_record.heart_rate
     * @mbg.generated
     */
    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.classification
     *
     * @return the value of t_medical_record.classification
     * @mbg.generated
     */
    public Integer getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.classification
     *
     * @param classification the value for t_medical_record.classification
     * @mbg.generated
     */
    public void setClassification(Integer classification) {
        this.classification = classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.create_by
     *
     * @return the value of t_medical_record.create_by
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.create_by
     *
     * @param createBy the value for t_medical_record.create_by
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_deleted
     *
     * @return the value of t_medical_record.is_deleted
     * @mbg.generated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_deleted
     *
     * @param isDeleted the value for t_medical_record.is_deleted
     * @mbg.generated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_code
     *
     * @return the value of t_medical_record.medical_code
     * @mbg.generated
     */
    public String getMedicalCode() {
        return medicalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_code
     *
     * @param medicalCode the value for t_medical_record.medical_code
     * @mbg.generated
     */
    public void setMedicalCode(String medicalCode) {
        this.medicalCode = medicalCode == null ? null : medicalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.report_status
     *
     * @return the value of t_medical_record.report_status
     * @mbg.generated
     */
    public Integer getReportStatus() {
        return reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.report_status
     *
     * @param reportStatus the value for t_medical_record.report_status
     * @mbg.generated
     */
    public void setReportStatus(Integer reportStatus) {
        this.reportStatus = reportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.device_code
     *
     * @return the value of t_medical_record.device_code
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.device_code
     *
     * @param deviceCode the value for t_medical_record.device_code
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.share_id
     *
     * @return the value of t_medical_record.share_id
     * @mbg.generated
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.share_id
     *
     * @param shareId the value for t_medical_record.share_id
     * @mbg.generated
     */
    public void setShareId(String shareId) {
        this.shareId = shareId == null ? null : shareId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_remote
     *
     * @return the value of t_medical_record.is_remote
     * @mbg.generated
     */
    public Integer getIsRemote() {
        return isRemote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_remote
     *
     * @param isRemote the value for t_medical_record.is_remote
     * @mbg.generated
     */
    public void setIsRemote(Integer isRemote) {
        this.isRemote = isRemote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.remarks
     *
     * @return the value of t_medical_record.remarks
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.remarks
     *
     * @param remarks the value for t_medical_record.remarks
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    @Override
    public String toString() {
        return "病历（ID=" + this.recordId + "）";
    }
}