package com.terrydr.dao.basic;

import com.terrydr.domain.AIResult;
import com.terrydr.domain.AIResultKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AIResultDAO {

    int count();

    List<AIResult> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    List<AIResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AIResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    int insert(AIResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    int insertSelective(AIResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    AIResult selectByPrimaryKey(AIResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AIResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AIResult record);
}