package com.terrydr.dao.basic;

import com.terrydr.domain.AIResult;
import com.terrydr.domain.AITask;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AITaskDAO {
    int count();

    List<AITask> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    List<AITask> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    int insert(AITask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    int insertSelective(AITask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    AITask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AITask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ai_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AITask record);
}