package com.terrydr.dao.basic;

import com.terrydr.domain.MedicalRecordAttr;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
@Repository
public interface MedicalRecordAttrDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    int insert(MedicalRecordAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    int insertSelective(MedicalRecordAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    MedicalRecordAttr selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MedicalRecordAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MedicalRecordAttr record);

}