package com.terrydr.dao.basic;

import com.terrydr.domain.MedicalRecordValue;
import org.springframework.stereotype.Repository;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
@Repository
public interface MedicalRecordValueDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    int insert(MedicalRecordValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    int insertSelective(MedicalRecordValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    MedicalRecordValue selectByPrimaryKey(String valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MedicalRecordValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MedicalRecordValue record);
}