package com.terrydr.dao.basic;

import com.terrydr.domain.MedicalRecord;
import com.terrydr.domain.MedicalRecordDetail;
import com.terrydr.domain.ecg.ECGMedicalRecord_UpdateAttrValue;
import com.terrydr.domain.ecg.MedicalRecord_UpdateRedundant;
import com.terrydr.domain.eye.EYEConsultation;
import com.terrydr.domain.eye.EYEMedicalRecord_UpdateAttrValue;
import com.terrydr.domain.pathology.PathologyMedicalRecord_UpdateAttrValue;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
@Repository
public interface MedicalRecordDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int insert(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int insertSelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    MedicalRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MedicalRecord record);

    /**
     * 分页查询
     * @return
     */
    List<MedicalRecordDetail> selectPerPageByType(@Param("offset") int offset, @Param("rows") int rows, @Param("type") int[] type);

    /**
     * 全部查询
     * @return
     */
    List<MedicalRecordDetail> selectAllByType(@Param("type") int[] type);

    /**
     * 查询总数
     * @return
     */
    int countByType(@Param("type") int[] type);

    /**
     * 分页查询
     * @return
     */
    List<MedicalRecordDetail> selectPerPageWithoutType(@Param("offset") int offset, @Param("rows") int rows, @Param("type") int[] type);

    /**
     * 全部查询
     * @return
     */
    List<MedicalRecordDetail> selectAllWithoutType(@Param("type") int[] type);

    /**
     * 查询总数
     * @return
     */
    int countWithoutType(@Param("type") int[] type);

    /**
     * 返回HeartRate
     * @return
     */
    List<ECGMedicalRecord_UpdateAttrValue> selectAttrValue4HeartRate();

    /**
     * 返回Classification
     * @return
     */
    List<ECGMedicalRecord_UpdateAttrValue> selectAttrValue4Classification();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeLeftVision();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeRightVision();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeLeftImg();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeRightImg();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeLeftVideo();

    /**
     * 返回Classification
     * @return
     */
    List<EYEMedicalRecord_UpdateAttrValue> selectAttrValue4EyeRightVideo();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4SubmitDepartment();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4SubmitUnit();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4SubmitDoctor();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4SubmitDate();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4SubmitMaterial();

    /**
     * 返回Classification
     * @return
     */
    List<PathologyMedicalRecord_UpdateAttrValue> selectAttrValue4VisualFeature();

    /**
     * 返回冗余字段
     * @return
     */
    List<MedicalRecord_UpdateRedundant> selectRedundant4ECGMedicalRecord();

    /**
     * 返回冗余字段
     * @return
     */
    List<MedicalRecord_UpdateRedundant> selectRedundant4EYEMedicalRecord();

    List<EYEConsultation> selectEyeConsultationFromProcess();
}