package com.terrydr.dao.basic;

import com.terrydr.domain.PathologyInfo;
import com.terrydr.domain.PathologyInfoDetail;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("pD")
public interface PathologyInfoDetailDAO {

    int count();

    List<PathologyInfoDetail> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    List<PathologyInfoDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info_detail
     *
     * @mbg.generated
     */
    int insert(PathologyInfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info_detail
     *
     * @mbg.generated
     */
    int insertSelective(PathologyInfoDetail record);
}