package com.terrydr.dao.basic;

import com.terrydr.domain.PathologyConsultation;
import com.terrydr.domain.PathologyInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("p")
public interface PathologyInfoDAO {

    int count();

    List<PathologyInfo> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    List<PathologyInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    int insert(PathologyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    int insertSelective(PathologyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    PathologyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PathologyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PathologyInfo record);
}