package com.terrydr.dao.basic;

import com.terrydr.domain.ReportAttr;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
@Repository
public interface ReportAttrDAO {

    List<ReportAttr> selectWithoutAttrId(@Param("ids") int[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    int insert(ReportAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    int insertSelective(ReportAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    ReportAttr selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportAttr record);

    int updateReportAttrStatus(@Param("ids") int[] ids);
}