package com.terrydr.dao.basic;

import com.terrydr.domain.ReportAttr;
import com.terrydr.domain.ReportValue;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @desc 描述 <br>
 * <p>
 * Copyright: Copyright (c)
 * <p>
 * Company: 南京泰立瑞信息科技有限公司
 * <p>
 * @author zyyan@terrydr.com
 * @version 1.0.0
 */
@Repository
public interface ReportValueDAO {
    List<ReportValue> selectWithoutAttrId(@Param("ids") int[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    int insert(ReportValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    int insertSelective(ReportValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    ReportValue selectByPrimaryKey(Integer valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReportValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReportValue record);
}