package com.terrydr.dao.basic;

import com.terrydr.domain.AITask;
import com.terrydr.domain.ScreenInterval;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ScreenIntervalDAO {

    int count();

    List<ScreenInterval> selectPerPage(@Param("offset") int offset, @Param("rows") int rows);

    List<ScreenInterval> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insert(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int insertSelective(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    ScreenInterval selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScreenInterval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_interval
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScreenInterval record);
}