package com.terrydr.dao.pathology;

import com.terrydr.domain.pathology.PathologyConsultation;
import org.springframework.stereotype.Repository;

@Repository
public interface PathConsultationDAO {

    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insert(PathologyConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int insertSelective(PathologyConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    PathologyConsultation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PathologyConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consultation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PathologyConsultation record);
}