package com.terrydr.dao.pathology;

import com.terrydr.domain.pathology.PathologyDetail;
import org.springframework.stereotype.Repository;

@Repository
public interface PathPathologyInfoDetailDAO {

    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info_detail
     *
     * @mbg.generated
     */
    int insert(PathologyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pathology_info_detail
     *
     * @mbg.generated
     */
    int insertSelective(PathologyDetail record);
}